    --drop table "APP"."CARNET_LICENCIAS";
    create table "APP"."CARNET_LICENCIAS"(
       "CLI_ID" BIGINT NOT NULL GENERATED BY DEFAULT AS identity,        
       "PER_APELLIDO" VARCHAR(80) not null,
       "PER_NOMBRE" VARCHAR(160) not null,
       "PER_TIPO_DOC" VARCHAR(30) not null,
       "PER_NUMERO_DOC" VARCHAR(30) not null,
       "PER_NACIONALIDAD" VARCHAR(40) not null,
       "PER_FECHA_NACIMIENTO" TIMESTAMP not null,
       "PER_GRUPO_SANGUINEO" VARCHAR(12) not null,
       "PER_TELEFONO" VARCHAR(40),
       "PER_DONANTE" VARCHAR(4) not null,
       "PER_ALERGIA" VARCHAR(80) not null,
       "PER_RESTRICCIONES" VARCHAR(100) not null,
       "PER_MEDICACION" VARCHAR(80) not null,
       "PER_DOMICILIO" VARCHAR(200) not null,
       "PER_OBSERVACIONES" VARCHAR(200),
       "PER_FOTO" BLOB,
       "PER_FIRMA" BLOB,
       "LIC_CLASE" VARCHAR(20) not null,
       "LIC_TRAMITE" VARCHAR(32) not null,
       "LIC_FECHA_OTORGADA" TIMESTAMP not null,
       "LIC_FECHA_VENCIMIENTO" TIMESTAMP not null,
       "USR_NOMBRE" VARCHAR(100) not null,
       "USR_CARGO" VARCHAR(100) not null,
       "USR_FIRMA" BLOB,
       "LIC_COD_LICENCIA" VARCHAR(50) not null,
       "MNC_NOMBRE" VARCHAR(200),
       "MNC_CODIGO" VARCHAR(200),
       "MNC_ESCUDO" BLOB,
       "CLI_FECHA_IMPRESION" TIMESTAMP,
       "CLI_FECHA_IMPORT" TIMESTAMP,
       "CLI_CANT_IMPRESIONES" BIGINT,
       "LIC_CLASE_DESC" VARCHAR(510),
        constraint "SQL110326234107330" primary key ("CLI_ID")
    );

    create unique index "SQL100626150010120" on "APP"."CARNET_LICENCIAS"("CLI_ID");   
  
	--drop table "APP"."CLASE_LICENCIA";
    create table "APP"."CLASE_LICENCIA"(
        "CLL_ID" BIGINT NOT NULL GENERATED BY DEFAULT AS identity ( START WITH 100000),
       "CLL_NOMBRE_CLASE" VARCHAR(20) not null unique,
       "CLL_VIGENCIA_PREDETERMINADA" BIGINT not null,
       "CLL_EDAD_MINIMA" BIGINT not null,
       "CLL_EDAD_MAXIMA" BIGINT not null,
       "CLL_DESCRIPCION_CORTA" VARCHAR(50) not null,
       "CLL_DESCRIPCION" VARCHAR(510) not null,
       "CLL_IMPORTEX6MESES" NUMERIC(15,2),
       "CLL_IMPORTEX12MESES" NUMERIC(15,2),
       "CLL_IMPORTEX24MESES" NUMERIC(15,2),
       "CLL_IMPORTEX36MESES" NUMERIC(15,2),
       "CLL_IMPORTEX48MESES" NUMERIC(15,2),
       "CLL_IMPORTEX60MESES" NUMERIC(15,2),
        constraint "SQL100613164858120" primary key ("CLL_ID")
    );

    create unique index "SQL100626213635800" on "APP"."CLASE_LICENCIA"("CLL_ID");
    create unique index "SQL100704162316390" on "APP"."CLASE_LICENCIA"("CLL_NOMBRE_CLASE");

	--drop table "APP"."ANTECEDENTE";
    create table "APP"."ANTECEDENTE"(
        "ANT_ID"  BIGINT NOT NULL GENERATED BY DEFAULT AS identity,
       "ANT_DESCRIPCION" VARCHAR(92) not null,
       "ANT_APRUEBA_SN" VARCHAR(2) not null,
        constraint "SQL100613164853420" primary key ("ANT_ID")
    );
    create unique index "SQL100625204414700" on "APP"."ANTECEDENTE"("ANT_ID");
   
   	--drop table "APP"."CAJA";
    create table "APP"."CAJA"(
       "CAJ_ID" BIGINT not null generated by default as identity ( START WITH 100000),
		"CAJ_IMPORTE" NUMERIC(15,2), 
		"LIC_ID" BIGINT not null,
		"CAJ_OBSERVACIONES" VARCHAR(200),
		"CAJ_RECIBO" BIGINT not null,
		"CAJ_FECHA" TIMESTAMP not null,
		constraint "SQL100413164854421" primary key ("CAJ_ID")
	);

	--drop table "APP"."PERSONA";
    create table "APP"."PERSONA"(
       "PER_ID" BIGINT NOT NULL GENERATED BY DEFAULT AS identity ( START WITH 100000),
       "PER_APELLIDO" VARCHAR(80) not null,
       "PER_NOMBRE" VARCHAR(160) not null,
       "PER_TIPO_DOC" VARCHAR(30) not null,
       "PER_NUMERO_DOC" VARCHAR(30) not null,
       "PER_NACIONALIDAD" VARCHAR(40) not null,
       "PER_SEXO" VARCHAR(2) not null,
       "PER_FECHA_NACIMIENTO" TIMESTAMP not null,
       "PER_GRUPO_SANGUINEO" VARCHAR(12) not null,
       "PER_TELEFONO" VARCHAR(40),
       "PER_DONANTE" VARCHAR(4) not null,
       "PER_ALERGIA" VARCHAR(80) not null,
       "PER_RESTRICCIONES" VARCHAR(100) not null,
       "PER_MEDICACION" VARCHAR(80) not null,
       "PER_DOMICILIO" VARCHAR(200) not null,
       "PER_OBSERVACIONES" VARCHAR(200),
       "PER_FOTO" BLOB,
       "PER_FIRMA" BLOB,
        constraint "SQL100326234107330" primary key ("PER_ID")
    );

    create unique index "SQL100625204313720" on "APP"."PERSONA"("PER_ID");
    
   	--drop table "APP"."USUARIO";
    create table "APP"."USUARIO"(
        "USR_ID"  BIGINT NOT NULL GENERATED BY DEFAULT AS identity ( START WITH 100000),
       "USR_NOMBRE" VARCHAR(100) not null unique,
       "USR_CARGO" VARCHAR(100) not null,
       "USR_CLAVE" VARCHAR(100) not null,
       "USR_ULTIMO_ACCESO" TIMESTAMP,
       "USR_HABILITADO_SN" VARCHAR(1) not null,
       "USR_PUEDE_FIRMAR_SN" VARCHAR(1) not null,
       "USR_ACC_PANEL_CONTROL_SN" VARCHAR(1) not null,
       "USR_ADM_USR_SN" VARCHAR(1) not null,
       "USR_RESTAURAR_BACK_SN" VARCHAR(1) not null,
       "USR_RESETEAR_SN" VARCHAR(1) not null,
       "USR_MODIFICAR_LIC_SN" VARCHAR(1) not null,
       "USR_AUTORIZADO_SN" VARCHAR(1) not null,
       "USR_CONTROL_ADM_SN" VARCHAR(1) not null,
       "DELETED_SN" VARCHAR(1) not null,
       "USR_FIRMA" BLOB,
        constraint "SQL101326234106450" primary key ("USR_ID")
    );
    create unique index "SQL100625204259470" on "APP"."USUARIO"("USR_ID");
    create unique index "SQL101426234106450" on "APP"."USUARIO"("USR_NOMBRE");


	--drop table "APP"."LICENCIA";
    create table "APP"."LICENCIA"(
        "LIC_ID" BIGINT NOT NULL GENERATED BY DEFAULT AS identity ( START WITH 100000),
       "LIC_OBSERVACIONES" VARCHAR(80),
       "LIC_CLASE" VARCHAR(20) not null,
       "LIC_TRAMITE" VARCHAR(32) not null,
       "LIC_FECHA_OTORGADA" TIMESTAMP not null,
       "LIC_FECHA_VENCIMIENTO" TIMESTAMP not null,
       "LIC_ESTADO" VARCHAR(2) not null,
       "USR_NOMBRE_FIRMA" BIGINT not null,
       "LIC_EXAMEN_TEORICO" VARCHAR(20) not null,
       "LIC_EXAMEN_PRACTICO" VARCHAR(20) not null,
       "ANT_ID" BIGINT not null,
       "LIC_DEUDA_SN" VARCHAR(1) not null,
       "USR_NOMBRE_RESPONSABLE" BIGINT not null,
       "LIC_FECHA_REAL" TIMESTAMP not null,
       "LIC_REQUISITOS_SN" VARCHAR(1) not null,
       "LIC_NUMERO" BIGINT not null,
       "LIC_COD_LICENCIA" VARCHAR(50) not null,
       "USR_CONFECCIONO_LICENCIA" BIGINT not null,
       "PER_ID_TITULAR" BIGINT not null,
       "LIC_EXAMEN_MEDICO" VARCHAR(34) not null,
       "LIC_EXAMEN_OFTALMOLOGICO" VARCHAR(34) not null,
       "LIC_EXAMEN_PSICOFISICO" VARCHAR(34) not null,
        constraint "SQL100613164854421" primary key ("LIC_ID")
    );

    create unique index "SQL100625204248730" on "APP"."LICENCIA"("LIC_ID");
    create index "SQL100625204431790" on "APP"."LICENCIA"("USR_NOMBRE_FIRMA");
    create index "SQL100625204431910" on "APP"."LICENCIA"("ANT_ID");
    create index "SQL100625204432020" on "APP"."LICENCIA"("USR_NOMBRE_RESPONSABLE");
    create index "SQL100625204432130" on "APP"."LICENCIA"("USR_CONFECCIONO_LICENCIA");
    create index "SQL100625204432240" on "APP"."LICENCIA"("PER_ID_TITULAR");

	--drop table "APP"."AUDITORIA";
    create table "APP"."AUDITORIA"(
        "AUD_ID" BIGINT not null generated always as identity,
       "AUD_ACCION" VARCHAR(200) not null,
       "AUD_OBJETO" VARCHAR(200),
       "AUD_FK" VARCHAR(100),
       "AUD_FECHA" TIMESTAMP not null,
       "AUD_USUARIO" VARCHAR(200) not null,
       "AUD_ESTACION" VARCHAR(200) not null,
        constraint "SQL100216215716790" primary key ("AUD_ID")
    );
    create unique index "SQL100626213637630" on "APP"."AUDITORIA"("AUD_ID");

	--DROP table "APP"."DOMINIO";
    create table "APP"."DOMINIO"(
       "DOM_ID" BIGINT not null generated always as identity,
       "DOM_TIPO" VARCHAR(200),
       "DOM_CLAVE" VARCHAR(200),
       "DOM_CODIGO" VARCHAR(200),
       "DOM_VALOR_MOSTRAR" VARCHAR(200),
       "DOM_DESCRIPCION" VARCHAR(200),
        constraint "SQL100326234107160" primary key ("DOM_ID")
    );

    create unique index "SQL100605120001810" on "APP"."DOMINIO"("DOM_ID");
    
    create unique index "UNIQUE_DOMINIO" on "APP"."DOMINIO"("DOM_TIPO","DOM_CLAVE","DOM_CODIGO","DOM_VALOR_MOSTRAR","DOM_DESCRIPCION");

	--DROP table "APP"."PROPIEDAD";
    create table "APP"."PROPIEDAD"(
        "PROP_CLAVE" VARCHAR(200) not null,
       "PROP_VALOR" VARCHAR(200) not null,
       "PROP_BLOB" BLOB,
        constraint "SQL100307164231900" primary key ("PROP_CLAVE")
    );

    create unique index "SQL100605115933030" on "APP"."PROPIEDAD"("PROP_CLAVE");



ALTER TABLE APP.CAJA ADD CONSTRAINT fk_02020 FOREIGN KEY (LIC_ID) REFERENCES APP.LICENCIA(LIC_ID);
alter table "APP"."LICENCIA" add constraint "FK_00027" foreign key ("ANT_ID") references "APP"."ANTECEDENTE"("ANT_ID");
alter table "APP"."LICENCIA" add constraint "FK_01221" foreign key ("PER_ID_TITULAR") references "APP"."PERSONA"("PER_ID");
alter table "APP"."LICENCIA" add constraint "FK_00018" foreign key ("USR_CONFECCIONO_LICENCIA") references "APP"."USUARIO"("USR_ID");
alter table "APP"."LICENCIA" add constraint "FK_00017" foreign key ("USR_NOMBRE_RESPONSABLE") references "APP"."USUARIO"("USR_ID");
alter table "APP"."LICENCIA" add constraint "FK_01015" foreign key ("USR_NOMBRE_FIRMA") references "APP"."USUARIO"("USR_ID");