INSERT INTO APP.USUARIO values(-1,'Administrador Sistema','Administrador del Sistema','1',null,'S','N','S','S','S','S','S','N','S','N',NULL);


INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION) VALUES ('GRAL','Tipo Documento','DNI','DNI','DNI');    
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION)  VALUES ('GRAL','Tipo Documento','L.C','L.C','L.C');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION)  VALUES ('GRAL','Tipo Documento','L.E','L.E','L.E');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION)  VALUES ('GRAL','Tipo Documento','C.I','C.I','C.I');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION)  VALUES ('GRAL','Tipo Documento','Pasap','Pasap','Pasap');

INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION)  VALUES ('GRAL','Sexo','H','MASCULINO','MASCULINO');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION)  VALUES ('GRAL','Sexo','M','FEMENINO','FEMENINO');

INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION)  VALUES ('GRAL','Donante','SI','SI','SI');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION)  VALUES ('GRAL','Donante','NO','NO','SI');

INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION)  VALUES ('GRAL','Nacionalidad','Argentino','Argentino','Argentino');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION)  VALUES ('GRAL','Nacionalidad','Argentina','Argentina','Argentina');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION)  VALUES ('GRAL','Nacionalidad','Española','Española','Española');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION)  VALUES ('GRAL','Nacionalidad','Español','Español','Español');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION)  VALUES ('GRAL','Nacionalidad','Boliviana','Boliviana','Boliviana');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION)  VALUES ('GRAL','Nacionalidad','Boliviano','Boliviano','Boliviano');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION)  VALUES ('GRAL','Nacionalidad','Estadounidense','Estadounidense','Estadounidense');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION)  VALUES ('GRAL','Nacionalidad','Chilena','Chilena','Chilena');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION)  VALUES ('GRAL','Nacionalidad','Chileno','Chileno','Chileno');

INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION)  VALUES ('GRAL','Nacionalidad','Salvadoreña','Salvadoreña','Salvadoreña');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION)  VALUES ('GRAL','Nacionalidad','Salvadoreño','Salvadoreño','Salvadoreño');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION)  VALUES ('GRAL','Nacionalidad','Croata','Croata','Croata');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION)  VALUES ('GRAL','Nacionalidad','Irlandes','Irlandes','Irlandes');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION)  VALUES ('GRAL','Nacionalidad','Irlandesa','Irlandesa','Irlandesa');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION)  VALUES ('GRAL','Nacionalidad','Italiana','Italiana','Italiana');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION)  VALUES ('GRAL','Nacionalidad','Italiano','Italiano','Italiano');


INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION)  VALUES ('GRAL','Estado Civil','CASADO','CASADO','CASADO');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION)  VALUES ('GRAL','Estado Civil','SOLTERO','SOLTERO','SOLTERO');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION)  VALUES ('GRAL','Estado Civil','SEPARADO','SEPARADO','SEPARADO');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION)  VALUES ('GRAL','Estado Civil','VIUDO','VIUDO','VIUDO');

INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION)  VALUES ('GRAL','Grupo Sanguíneo','0 -','0 -','0 -');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION)  VALUES ('GRAL','Grupo Sanguíneo','0 +','0 +','0 +');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION)  VALUES ('GRAL','Grupo Sanguíneo','A -','A -','A -');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION)  VALUES ('GRAL','Grupo Sanguíneo','A +','A +','A +');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION)  VALUES ('GRAL','Grupo Sanguíneo','B -','B -','B -');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION)  VALUES ('GRAL','Grupo Sanguíneo','B +','B +','B +');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION)  VALUES ('GRAL','Grupo Sanguíneo','AB -','AB -','AB -');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION)  VALUES ('GRAL','Grupo Sanguíneo','AB +','AB +','AB +');

INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION)  VALUES ('RESTRICCION','Restricción Auditiva','Operación Auditiva','Operación Auditiva','Operación Auditiva');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION)  VALUES ('RESTRICCION','Restricción Auditiva','Usa Audífonos','Usa Audífonos','Usa Audífonos');

INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION) VALUES ('RESTRICCION','Restricción Física','Prótesis Superior','Prótesis Superior','Prótesis Superior');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION) VALUES ('RESTRICCION','Restricción Física','Prótesis Inferior','Prótesis Inferior','Prótesis Inferior');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION) VALUES ('RESTRICCION','Restricción Física','Afección Miembros Superiores','Afección Miembros Superiores','Afección Miembros Superiores');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION) VALUES ('RESTRICCION','Restricción Física','Afección Miembros Inferiores','Afección Miembros Inferiores','Afección Miembros Inferiores');

INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION) VALUES ('IMAGENES','EXTENCION_IMAGENES','png','png','png');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION) VALUES ('IMAGENES','EXTENCION_IMAGENES','jpg','jpg','jpg');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION) VALUES ('IMAGENES','EXTENCION_IMAGENES','jpeg','jpeg','jpeg');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION) VALUES ('IMAGENES','EXTENCION_IMAGENES','gif','gif','gif');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION) VALUES ('IMAGENES','EXTENCION_IMAGENES','tif','tif','tif');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION) VALUES ('IMAGENES','EXTENCION_IMAGENES','tiff','tiff','tiff');

INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION) VALUES ('EXAMEN','EXAMEN_ESTADO','Aprobado','Aprobado','Aprobado');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION) VALUES ('EXAMEN','EXAMEN_ESTADO','Exento','Exento','Exento');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION) VALUES ('EXAMEN','EXAMEN_ESTADO','Falta','Falta','Falta');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION) VALUES ('EXAMEN','EXAMEN_ESTADO','Reprobado','Reprobado','Reprobado');

INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION) VALUES ('EXAMEN','EXAMEN_MEDICO_ESTADO','Apto','Apto','Apto');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION) VALUES ('EXAMEN','EXAMEN_MEDICO_ESTADO','Apto con reservas','Apto con reservas','Apto con reservas');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION) VALUES ('EXAMEN','EXAMEN_MEDICO_ESTADO','Falta','Falta','Falta');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION) VALUES ('EXAMEN','EXAMEN_MEDICO_ESTADO','No apto','No apto','No apto');

INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION) VALUES ('LICENCIA','TIPO_TRAMITE','Renovación','Renovación','Renovación');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION) VALUES ('LICENCIA','TIPO_TRAMITE','Primer licencia','Primer licencia','Primer licencia');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION) VALUES ('LICENCIA','TIPO_TRAMITE','Modificada','Modificada','Modificada');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION) VALUES ('LICENCIA','TIPO_TRAMITE','Aprendizaje','Aprendizaje','Aprendizaje');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION) VALUES ('LICENCIA','TIPO_TRAMITE','Duplicado','Duplicado','Duplicado');

INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION) VALUES ('LICENCIA','DURACIONES_PREDETERMINADAS_LICENCIA','06','06','06');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION) VALUES ('LICENCIA','DURACIONES_PREDETERMINADAS_LICENCIA','12','12','12');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION) VALUES ('LICENCIA','DURACIONES_PREDETERMINADAS_LICENCIA','24','24','24');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION) VALUES ('LICENCIA','DURACIONES_PREDETERMINADAS_LICENCIA','36','36','36');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION) VALUES ('LICENCIA','DURACIONES_PREDETERMINADAS_LICENCIA','48','48','48');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION) VALUES ('LICENCIA','DURACIONES_PREDETERMINADAS_LICENCIA','60','60','60');

INSERT INTO APP.PROPIEDAD(PROP_CLAVE,PROP_VALOR) VALUES ('SISTEMA.UBICACION.LICENCIAS.IMPORTAR','S');

INSERT INTO APP.PROPIEDAD (PROP_CLAVE,PROP_VALOR) VALUES ('FORMATO.FECHA','dd-MM-yyyy');
INSERT INTO APP.PROPIEDAD (PROP_CLAVE,PROP_VALOR) VALUES ('FORMATO.HORA','HH:mm:ss');
INSERT INTO APP.PROPIEDAD (PROP_CLAVE,PROP_VALOR) VALUES ('FORMATO.FECHA.HORA','dd-MM-yyyy HH:mm:ss');
INSERT INTO APP.PROPIEDAD (PROP_CLAVE,PROP_VALOR) VALUES ('DIRECTORIO.IMAGENES','C:\\');
INSERT INTO APP.PROPIEDAD (PROP_CLAVE,PROP_VALOR) VALUES ('DIRECTORIO.BACKUP.PRIMARIO','D:\\');
INSERT INTO APP.PROPIEDAD (PROP_CLAVE,PROP_VALOR) VALUES ('DIRECTORIO.BACKUP.SECUNDARIO','C:\\');
INSERT INTO APP.PROPIEDAD (PROP_CLAVE,PROP_VALOR) VALUES ('DIRECTORIO.IMAGEN.FONDO.APLICACION','C:\\');
INSERT INTO APP.PROPIEDAD (PROP_CLAVE,PROP_VALOR) VALUES ('PERSONA.FOTO.REQUERIDA','S');
INSERT INTO APP.PROPIEDAD (PROP_CLAVE,PROP_VALOR) VALUES ('PERSONA.FIRMA.REQUERIDA','N');
INSERT INTO APP.PROPIEDAD (PROP_CLAVE,PROP_VALOR) VALUES ('PERSONA.DNI.MASCARA','##.###.###');
INSERT INTO APP.PROPIEDAD (PROP_CLAVE,PROP_VALOR) VALUES ('PERSONA.DNI.PERMITIR.SOLO.NUMEROS','S');
INSERT INTO APP.PROPIEDAD (PROP_CLAVE,PROP_VALOR) VALUES ('PERSONA.DNI.FIJAR.CANTIDAD.CARACTERES','S');
INSERT INTO APP.PROPIEDAD (PROP_CLAVE,PROP_VALOR) VALUES ('PERSONA.DNI.CANTIDAD.CARACTERES.FIJA','8');
INSERT INTO APP.PROPIEDAD (PROP_CLAVE,PROP_VALOR) VALUES ('SISTEMA.ACTUALIZACION.AUTOMATICA.INICIO','N');
INSERT INTO APP.PROPIEDAD (PROP_CLAVE,PROP_VALOR) VALUES ('SISTEMA.DEVICES.CAMARA','vfw:Microsoft WDM Image Capture (Win32):0');
INSERT INTO APP.PROPIEDAD (PROP_CLAVE,PROP_VALOR) VALUES ('SISTEMA.GUARDAR.LOG.EVENTOS','S');
INSERT INTO APP.PROPIEDAD (PROP_CLAVE,PROP_VALOR) VALUES ('SISTEMA.CONSERVAR.DATOS.LOG.EVENTOS.XDIAS','20');
INSERT INTO APP.PROPIEDAD (PROP_CLAVE,PROP_VALOR) VALUES ('SISTEMA.ORIGEN.FOTOS','DISCO');--DISCO WEBCAM EXISTE ENUM
INSERT INTO APP.PROPIEDAD (PROP_CLAVE,PROP_VALOR) VALUES ('SISTEMA.ORIGEN.FIRMAS','DISCO');--DISCO PAD EXISTE ENUM
INSERT INTO APP.PROPIEDAD (PROP_CLAVE,PROP_VALOR) VALUES ('SISTEMA.IMAGENES.PORCENTAJE.REDUCCION','25');
INSERT INTO APP.PROPIEDAD (PROP_CLAVE,PROP_VALOR) VALUES ('SISTEMA.FIRMAS.PORCENTAJE.REDUCCION','25');
INSERT INTO APP.PROPIEDAD (PROP_CLAVE,PROP_VALOR) VALUES ('SISTEMA.BACKUP.AUTOMATICO.ACTIVADO','N');
INSERT INTO APP.PROPIEDAD (PROP_CLAVE,PROP_VALOR) VALUES ('SISTEMA.BACKUP.AUTOMATICO.CADAXDIAS','20');
INSERT INTO APP.PROPIEDAD (PROP_CLAVE,PROP_VALOR) VALUES ('SISTEMA.BACKUP.SECUNDARIO.SI-NO','N');
INSERT INTO APP.PROPIEDAD (PROP_CLAVE,PROP_VALOR) VALUES ('SISTEMA.BACKUP.FECHAULTIMOBACKUP','28-04-2010');
INSERT INTO APP.PROPIEDAD (PROP_CLAVE,PROP_VALOR) VALUES ('SISTEMA.EMAIL.AUTOMATICO.IMPRESION.LICENCIAS','S');
INSERT INTO APP.PROPIEDAD (PROP_CLAVE,PROP_VALOR) VALUES ('SISTEMA.EMAIL.CENTRO.IMPRESION.LICENCIAS','jtesta@comininet.com.ar');
INSERT INTO APP.PROPIEDAD (PROP_CLAVE,PROP_VALOR) VALUES ('SISTEMA.NOMBRE.MUNICIPIO','Berrotarán');
INSERT INTO APP.PROPIEDAD (PROP_CLAVE,PROP_VALOR) VALUES ('SISTEMA.CODIGO.MUNICIPIO','290');
INSERT INTO APP.PROPIEDAD (PROP_CLAVE,PROP_VALOR) VALUES ('SISTEMA.IMAGEN.PRIMARIA','');
INSERT INTO APP.PROPIEDAD (PROP_CLAVE,PROP_VALOR) VALUES ('SISTEMA.FOTO.MUNICIPIO','');
INSERT INTO APP.PROPIEDAD (PROP_CLAVE,PROP_VALOR) VALUES ('SISTEMA.MUNICIPIO.ES_CENTRO_IMPRESOR_S_N','N');
INSERT INTO APP.PROPIEDAD(PROP_CLAVE,PROP_VALOR) VALUES ('SISTEMA.FTP_PRINCIPAL_URL','DXTEn5m2NtfIb0JrQ88tOwkSptl3lH87AJZPfePBh80=');
INSERT INTO APP.PROPIEDAD(PROP_CLAVE,PROP_VALOR) VALUES ('SISTEMA.FTP_PRINCIPAL_USER','K8l004OOY1J6Uup98Cp/pQ==');
INSERT INTO APP.PROPIEDAD(PROP_CLAVE,PROP_VALOR) VALUES ('SISTEMA.FTP_PRINCIPAL_PASSWORD','uLBg40t0YiQ9/9dBV8UgSg==');
INSERT INTO APP.PROPIEDAD(PROP_CLAVE,PROP_VALOR) VALUES ('SISTEMA.FTP_SECUNDARIO_URL','1yT7xdyXFOC1p1EecQ0V3Q==');
INSERT INTO APP.PROPIEDAD(PROP_CLAVE,PROP_VALOR) VALUES ('SISTEMA.FTP_SECUNDARIO_USER','sva1t1RMRadkMMoiRlpKWA==');
INSERT INTO APP.PROPIEDAD(PROP_CLAVE,PROP_VALOR) VALUES ('SISTEMA.FTP_SECUNDARIO_PASSWORD','WXr7F2JirExUiUzOnSAeyA==');
INSERT INTO APP.PROPIEDAD(PROP_CLAVE,PROP_VALOR) VALUES ('SISTEMA.NOMBRE.PROGRAMA','Autoimpresor');
INSERT INTO APP.PROPIEDAD(PROP_CLAVE,PROP_VALOR) VALUES ('SISTEMA.CODIGO_REGION_DESTINO','ar');
INSERT INTO APP.PROPIEDAD(PROP_CLAVE,PROP_VALOR) VALUES ('SISTEMA.VERSION_PRINCIPAL','v1');
INSERT INTO APP.PROPIEDAD(PROP_CLAVE,PROP_VALOR) VALUES ('SISTEMA.VALIDAR_REQUISITOS_SN','S');
INSERT INTO APP.PROPIEDAD(PROP_CLAVE,PROP_VALOR) VALUES ('SISTEMA.HASH_ULTIMO_ARCHIVO_SCRIPT_EJECUTADO','0');
INSERT INTO APP.PROPIEDAD(PROP_CLAVE,PROP_VALOR) VALUES ('SISTEMA.ULTIMO.FIRMANTE','');
INSERT INTO APP.PROPIEDAD(PROP_CLAVE,PROP_VALOR) VALUES ('MUNICIPIO.RANGO.LICENCIAS.DESDE','1000');
INSERT INTO APP.PROPIEDAD(PROP_CLAVE,PROP_VALOR) VALUES ('MUNICIPIO.RANGO.LICENCIAS.HASTA','2000');
INSERT INTO APP.PROPIEDAD(PROP_CLAVE,PROP_VALOR) VALUES ('MUNICIPIO.RANGO.LICENCIAS.AVISAR.CUANDO.FALTAN','100');


