/*
 * PanelAgudezaVisual.java
 *
 * Created on __DATE__, __TIME__
 */

package frontend.paneles.vision;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Set;

import javax.swing.ImageIcon;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JToggleButton;

import testerGeneral.business.ContextManager;
import testerGeneral.domain.Constantes;
import testerGeneral.domain.Examen;
import testerGeneral.domain.ExamenDetalle;
import testerGeneral.domain.PersonaExamen;
import testerGeneral.domain.Resultado;
import testerGeneral.domain.ResultadoDetalleExamen;
import testerGeneral.exceptions.ExceptionIsNotHadware;
import testerGeneral.service.ExamenDetalleDefinition;
import testerGeneral.service.PersonaExamenDefinition;
import testerGeneral.service.ResultadoDetalleExamenDefinition;
import testerGeneral.threads.ThreadTrama;
import examenes.psicometrico.domain.TramaVision;
import frontend.components.JOptionPaneTesterGral;
import frontend.paneles.examenes.Finalisable;
import frontend.paneles.examenes.PanelDetalleExamen;
import frontend.paneles.examenes.PanelExamen;
import frontend.utils.Util;

/**
 *
 * @author  __USER__
 */
public class PanelAgudezaVisual extends javax.swing.JPanel implements
		Finalisable, PanelExamen {

	private JToggleButton btn;
	private PersonaExamen personaExamen;
	private ExamenDetalle exaDetalle;
	private List<Resultado> resultados = new ArrayList<Resultado>();
	private static final int LINEA_PROFECIONAL = 6;
	private static final int LINEA_PARTICULAR = 5;
	private ThreadTrama thTrama;

	/** Creates new form PanelAgudezaVisual */
	public PanelAgudezaVisual(JToggleButton btn, PersonaExamen personaExamen) {
		this.btn = btn;
		this.personaExamen = personaExamen;
		initComponents();
		cargarImagenes();
		Util.mostrarError(lbError, null, true);

		try {
			ExamenDetalleDefinition examenDetalleService = (ExamenDetalleDefinition) ContextManager
					.getBizObject("examenDetalleService");
			exaDetalle = new ExamenDetalle();
			exaDetalle
					.setExadCodigo(ExamenDetalle.EXAD_CODIGO_TEST_AGUDEZA_VISUAL);
			exaDetalle = (ExamenDetalle) examenDetalleService
					.getAll(exaDetalle).get(0);

		} catch (Exception e) {
			throw new RuntimeException(e);
		}

		inicializarThreads();
	}

	public void inicializarThreads() {

		try {
			if (Util.thTrama == null) {
				thTrama = new ThreadTrama(new TramaVision());
				thTrama.setEjecutar(false);
				Util.thTrama = thTrama;
				thTrama.setEjecucion(99999);
				thTrama.start();

				thTrama.sendOrden(ThreadTrama.ORDEN_CAMBIA_ESTADO_LUZ_IZQ);
				Thread.sleep(20);
				thTrama.sendOrden(ThreadTrama.ORDEN_CAMBIA_ESTADO_LUZ_DER);
				Thread.sleep(20);
				thTrama.sendOrden(0x5050);
				Thread.sleep(250);

			} else
				thTrama = Util.thTrama;

			thTrama.sendOrden(ThreadTrama.ORDEN_IR_TEST1);

		} catch (ExceptionIsNotHadware e) {
			JOptionPaneTesterGral.showInternalMessageDialog(e.getMessage(),
					"Error", JOptionPane.ERROR_MESSAGE);
		} catch (Exception e) {
			throw new RuntimeException(e);
		}

	}

	public void cargarImagenes() {
		String binocular = ContextManager
				.getProperty("EXAMEN.AGUDEZA.VISUAL.IMG.BONOCULAR");
		String monoIzq = ContextManager
				.getProperty("EXAMEN.AGUDEZA.VISUAL.IMG.MONOCULAR.IZQ");
		String monoDer = ContextManager
				.getProperty("EXAMEN.AGUDEZA.VISUAL.IMG.MONOCULAR.DER");
		Util.setIcon(lbBinocular, binocular);
		Util.setIcon(lbMonoIzq, monoIzq);
		Util.setIcon(lbMonoDer, monoDer);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		buttonGroup1 = new javax.swing.ButtonGroup();
		buttonGroup2 = new javax.swing.ButtonGroup();
		jPanel1 = new javax.swing.JPanel();
		lbBinocular = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jFormattedLineaBinocular = new javax.swing.JFormattedTextField();
		jRadioBoxBinocular = new javax.swing.JRadioButton();
		jLabel7 = new javax.swing.JLabel();
		jFormattedLineaBinocularLe = new javax.swing.JFormattedTextField();
		jPanel2 = new javax.swing.JPanel();
		lbMonoIzq = new javax.swing.JLabel();
		jFormattedMonoIzq = new javax.swing.JFormattedTextField();
		jRadioBoxMonoIzq = new javax.swing.JRadioButton();
		jLabel3 = new javax.swing.JLabel();
		jFormattedLineaMonocularIzqLe = new javax.swing.JFormattedTextField();
		jLabel8 = new javax.swing.JLabel();
		jPanel3 = new javax.swing.JPanel();
		lbMonoDer = new javax.swing.JLabel();
		jFormattedMonoDer = new javax.swing.JFormattedTextField();
		jRadioBoxMonoDer = new javax.swing.JRadioButton();
		jLabel4 = new javax.swing.JLabel();
		jFormattedLineaMonocularDerLe = new javax.swing.JFormattedTextField();
		jLabel9 = new javax.swing.JLabel();
		btnGuardar = new javax.swing.JToggleButton();
		lbError = new javax.swing.JLabel();
		jRadioExamenCercana = new javax.swing.JRadioButton();
		jRadioExamenLejana = new javax.swing.JRadioButton();

		setBorder(javax.swing.BorderFactory.createTitledBorder(""));
		addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusGained(java.awt.event.FocusEvent evt) {
				formFocusGained(evt);
			}
		});

		jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

		lbBinocular.setBackground(new java.awt.Color(51, 51, 255));
		lbBinocular
				.setIcon(new javax.swing.ImageIcon(
						"C:\\programacion\\Workspaces3\\TesterGeneral\\images\\images\\vision\\agudeza visual\\binocular.png")); // NOI18N

		jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14));
		jLabel2.setForeground(new java.awt.Color(0, 0, 255));
		jLabel2.setText("L\u00ednea correcta visi\u00f3n cercana:");

		try {
			jFormattedLineaBinocular
					.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(
							new javax.swing.text.MaskFormatter("#")));
		} catch (java.text.ParseException ex) {
			ex.printStackTrace();
		}
		jFormattedLineaBinocular
				.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);

		buttonGroup2.add(jRadioBoxBinocular);
		jRadioBoxBinocular.setSelected(true);
		jRadioBoxBinocular.setText("Visi\u00f3n binocular");

		jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 14));
		jLabel7.setForeground(new java.awt.Color(0, 0, 255));
		jLabel7.setText("L\u00ednea correcta visi\u00f3n lejana:");

		try {
			jFormattedLineaBinocularLe
					.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(
							new javax.swing.text.MaskFormatter("#")));
		} catch (java.text.ParseException ex) {
			ex.printStackTrace();
		}
		jFormattedLineaBinocularLe.setEnabled(false);
		jFormattedLineaBinocularLe
				.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(lbBinocular)
						.addComponent(jRadioBoxBinocular)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel7)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jFormattedLineaBinocularLe,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				31,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel2)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jFormattedLineaBinocular,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				31,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addComponent(jRadioBoxBinocular)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												lbBinocular,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												251,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel2)
														.addComponent(
																jFormattedLineaBinocular,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel7)
														.addComponent(
																jFormattedLineaBinocularLe,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap(35, Short.MAX_VALUE)));

		jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

		lbMonoIzq.setBackground(new java.awt.Color(153, 0, 0));
		lbMonoIzq
				.setIcon(new javax.swing.ImageIcon(
						"C:\\programacion\\Workspaces3\\TesterGeneral\\images\\images\\vision\\agudeza visual\\monocular_izq.png")); // NOI18N

		try {
			jFormattedMonoIzq
					.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(
							new javax.swing.text.MaskFormatter("#")));
		} catch (java.text.ParseException ex) {
			ex.printStackTrace();
		}
		jFormattedMonoIzq.setEnabled(false);
		jFormattedMonoIzq
				.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);

		buttonGroup2.add(jRadioBoxMonoIzq);
		jRadioBoxMonoIzq.setText("Visi\u00f3n monocular izquierdo");

		jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14));
		jLabel3.setForeground(new java.awt.Color(0, 0, 255));
		jLabel3.setText("L\u00ednea correcta visi\u00f3n cercana:");

		try {
			jFormattedLineaMonocularIzqLe
					.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(
							new javax.swing.text.MaskFormatter("#")));
		} catch (java.text.ParseException ex) {
			ex.printStackTrace();
		}
		jFormattedLineaMonocularIzqLe.setEnabled(false);
		jFormattedLineaMonocularIzqLe
				.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);

		jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 14));
		jLabel8.setForeground(new java.awt.Color(0, 0, 255));
		jLabel8.setText("L\u00ednea correcta visi\u00f3n lejana:");

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout
				.setHorizontalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addContainerGap()
																		.addComponent(
																				lbMonoIzq))
														.addComponent(
																jRadioBoxMonoIzq)
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addContainerGap()
																		.addComponent(
																				jLabel3)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jFormattedMonoIzq,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				31,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE))
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel2Layout
										.createSequentialGroup()
										.addContainerGap(22, Short.MAX_VALUE)
										.addComponent(jLabel8)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jFormattedLineaMonocularIzqLe,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												31,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap()));
		jPanel2Layout
				.setVerticalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addComponent(jRadioBoxMonoIzq)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(lbMonoIzq)
										.addGap(18, 18, 18)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jFormattedMonoIzq,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel3))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jFormattedLineaMonocularIzqLe,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel8))
										.addContainerGap(34, Short.MAX_VALUE)));

		jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

		lbMonoDer.setBackground(new java.awt.Color(0, 153, 153));
		lbMonoDer
				.setIcon(new javax.swing.ImageIcon(
						"C:\\programacion\\Workspaces3\\TesterGeneral\\images\\images\\vision\\agudeza visual\\monocular_der.png")); // NOI18N

		try {
			jFormattedMonoDer
					.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(
							new javax.swing.text.MaskFormatter("#")));
		} catch (java.text.ParseException ex) {
			ex.printStackTrace();
		}
		jFormattedMonoDer.setEnabled(false);
		jFormattedMonoDer
				.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);

		buttonGroup2.add(jRadioBoxMonoDer);
		jRadioBoxMonoDer.setText("Visi\u00f3n monocular derecho");

		jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 14));
		jLabel4.setForeground(new java.awt.Color(0, 0, 255));
		jLabel4.setText("L\u00ednea correcta visi\u00f3n cercana:");

		try {
			jFormattedLineaMonocularDerLe
					.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(
							new javax.swing.text.MaskFormatter("#")));
		} catch (java.text.ParseException ex) {
			ex.printStackTrace();
		}
		jFormattedLineaMonocularDerLe.setEnabled(false);
		jFormattedLineaMonocularDerLe
				.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);

		jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 14));
		jLabel9.setForeground(new java.awt.Color(0, 0, 255));
		jLabel9.setText("L\u00ednea correcta visi\u00f3n lejana:");

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(
				jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout
				.setHorizontalGroup(jPanel3Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel3Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jRadioBoxMonoDer)
														.addComponent(lbMonoDer)
														.addGroup(
																jPanel3Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel4)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jFormattedMonoDer,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				31,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																jPanel3Layout
																		.createSequentialGroup()
																		.addGap(
																				10,
																				10,
																				10)
																		.addComponent(
																				jLabel9)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jFormattedLineaMonocularDerLe,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				31,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));
		jPanel3Layout
				.setVerticalGroup(jPanel3Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel3Layout
										.createSequentialGroup()
										.addComponent(jRadioBoxMonoDer)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(lbMonoDer)
										.addGap(18, 18, 18)
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jFormattedMonoDer,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel4))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jFormattedLineaMonocularDerLe,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel9))
										.addContainerGap(36, Short.MAX_VALUE)));

		btnGuardar.setFont(new java.awt.Font("Segoe UI", 3, 14));
		btnGuardar.setForeground(new java.awt.Color(0, 0, 255));
		btnGuardar.setText("Guardar Resultados");
		btnGuardar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnGuardarActionPerformed(evt);
			}
		});

		lbError.setForeground(new java.awt.Color(204, 0, 0));
		lbError.setIcon(new ImageIcon(getClass().getResource(
				Constantes.IMG_ERROR)));
		lbError.setText(Constantes.ERROR_SIN_RESULTADOS);

		buttonGroup1.add(jRadioExamenCercana);
		jRadioExamenCercana.setFont(new java.awt.Font("Segoe UI", 3, 14));
		jRadioExamenCercana.setSelected(true);
		jRadioExamenCercana.setText("Examen de visi\u00f3n cercana");

		buttonGroup1.add(jRadioExamenLejana);
		jRadioExamenLejana.setFont(new java.awt.Font("Segoe UI", 3, 14));
		jRadioExamenLejana.setText("Examen de visi\u00f3n lejana");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								layout
										.createSequentialGroup()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																lbError,
																javax.swing.GroupLayout.Alignment.LEADING,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																642,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addComponent(
																				jPanel1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				324,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addComponent(
																								btnGuardar)
																						.addGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								layout
																										.createSequentialGroup()
																										.addComponent(
																												jPanel2,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												jPanel3,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												javax.swing.GroupLayout.PREFERRED_SIZE)))
																		.addGap(
																				0,
																				0,
																				0))
														.addGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																layout
																		.createSequentialGroup()
																		.addComponent(
																				jRadioExamenCercana,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				231,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jRadioExamenLejana)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
										.addContainerGap(159, Short.MAX_VALUE)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jRadioExamenCercana)
														.addComponent(
																jRadioExamenLejana))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																jPanel3,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																jPanel1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jPanel2,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																lbError,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																24,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																btnGuardar))
										.addContainerGap()));
	}// </editor-fold>
	//GEN-END:initComponents

	private void formFocusGained(java.awt.event.FocusEvent evt) {
		jFormattedLineaBinocular.requestFocus();
	}

	public boolean isExamenValid() {
		Util.mostrarError(lbError, null, true);

		if (jCheckBoxBinocular.isSelected()
				&& !isLineaValueValid(jFormattedLineaBinocular)) {
			Util
					.mostrarError(
							lbError,
							"Debe ingresar la línea correcta para binocular. Valores entre 1 y 7.",
							false);
			return false;
		} else if (jCheckBoxMonoIzq.isSelected()
				&& !isLineaValueValid(jFormattedMonoIzq)) {
			Util
					.mostrarError(
							lbError,
							"Debe ingresar la línea correcta para monocular izquierdo. Valores entre 1 y 7.",
							false);
			return false;
		} else if (jCheckBoxMonoDer.isSelected()
				&& !isLineaValueValid(jFormattedMonoDer)) {
			Util
					.mostrarError(
							lbError,
							"Debe ingresar la línea correcta para monocular derecho. Valores entre 1 y 7.",
							false);
			return false;
		}

		return true;
	}

	public boolean isLineaValueValid(JFormattedTextField jFormattedLinea) {
		try {
			int value = Integer.valueOf(jFormattedLinea.getText());
			if (value == 0 || value > 7)
				return false;
		} catch (NumberFormatException ex) {
			return false;
		}

		return true;
	}

	public void cargarResultados() {
		resultados.clear();
		Resultado res = new Resultado();
		res.setResEtapa(0l);
		if (jCheckBoxBinocular.isSelected()) {
			res.setResEtapaDesc("Visión binocular");
			res
					.setResValor1(Double.valueOf(jFormattedLineaBinocular
							.getText()));
			resultados.add(res);
		}

		res = new Resultado();
		res.setResEtapa(1l);
		if (jCheckBoxMonoIzq.isSelected()) {
			res.setResEtapaDesc("Visión monocular izquierdo");
			res.setResValor1(Double.valueOf(jFormattedMonoIzq.getText()));
			resultados.add(res);
		}

		res = new Resultado();
		res.setResEtapa(2l);
		if (jCheckBoxMonoDer.isSelected()) {
			res.setResEtapaDesc("Visión monocular derecho");
			res.setResValor1(Double.valueOf(jFormattedMonoDer.getText()));
			resultados.add(res);
		}
	}

	public String getResultado() {
		if (jCheckBoxBinocular.isSelected()) {
			int lineaBinocular = Integer.valueOf(jFormattedLineaBinocular
					.getText());
			if (!isAprobed(lineaBinocular))
				return Examen.RESULTADO_FUERA;
		}

		if (jCheckBoxMonoIzq.isSelected()) {
			int lineaMonoIzq = Integer.valueOf(jFormattedMonoIzq.getText());
			if (!isAprobed(lineaMonoIzq))
				return Examen.RESULTADO_FUERA;
		}

		if (jCheckBoxMonoDer.isSelected()) {
			int lineaMonoDer = Integer.valueOf(jFormattedMonoDer.getText());
			if (!isAprobed(lineaMonoDer))
				return Examen.RESULTADO_FUERA;
		}

		return Examen.RESULTADO_DENTRO;
	}

	public boolean isAprobed(int valor) {
		if (this.personaExamen.getPexaTipoExamen().equals("Profesional")
				&& valor < LINEA_PROFECIONAL)
			return false;

		if (this.personaExamen.getPexaTipoExamen().equals("Particular")
				&& valor < LINEA_PARTICULAR)
			return false;

		return true;
	}

	private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {
		btnGuardar.setSelected(false);
		ResultadoDetalleExamenDefinition resultadoDetalleExamenService = (ResultadoDetalleExamenDefinition) ContextManager
				.getBizObject("resultadoDetalleExamenService");
		PersonaExamenDefinition personaExamenService = (PersonaExamenDefinition) ContextManager
				.getBizObject("personaExamenService");

		try {

			if (personaExamen != null && personaExamen.getPexaId() == null) {
				personaExamen.setPexaEstado("INICIADO");
				personaExamen.setPexaFecha(new Date());
				personaExamenService.insert(personaExamen);
			}

			if (isExamenValid()) {
				ResultadoDetalleExamen resultadoDetalleExamen = new ResultadoDetalleExamen();
				resultadoDetalleExamen.setExamenDetalle(exaDetalle);
				resultadoDetalleExamen.setPersonaExamen(personaExamen);
				List lstResultados = resultadoDetalleExamenService
						.getAll(resultadoDetalleExamen);

				if (lstResultados.size() < 1) {
					resultadoDetalleExamenService
							.insert(resultadoDetalleExamen);
				} else if (lstResultados.size() == 1) {
					resultadoDetalleExamen = (ResultadoDetalleExamen) lstResultados
							.get(0);
				}

				cargarResultados();
				String detalleResultado = "<HTML>";
				Set setResultados = resultadoDetalleExamen.getResultados();
				setResultados.clear();
				for (int i = 0; i < this.resultados.size(); i++) {
					this.resultados.get(i).setResultadoDetalleExamen(
							resultadoDetalleExamen);
					setResultados.add(this.resultados.get(i));
					detalleResultado = detalleResultado
							+ this.resultados.get(i).getResEtapaDesc() + ": "
							+ this.resultados.get(i).getResValor1().intValue()
							+ ".<BR>";
				}

				String resultado = getResultado();

				resultadoDetalleExamen.setRdeResultado(resultado);
				resultadoDetalleExamen.setRdeDetalleResultado(detalleResultado
						+ "</HTML>");

				resultadoDetalleExamenService.update(resultadoDetalleExamen);

				btn.setForeground(Color.BLACK);
				Util.setIcon(btn, Constantes.IMG_ACEPTAR_SMALL);

				((PanelDetalleExamen) btn.getParent()).nextExamen(btn);
			}

		} catch (Exception e) {
			throw new RuntimeException(e);
		}
	}

	private void jCheckBoxMonoDerActionPerformed(java.awt.event.ActionEvent evt) {
		if (!jCheckBoxMonoDer.isSelected()) {
			jFormattedMonoDer.setEnabled(false);
			jFormattedMonoDer.setText(null);
		} else
			jFormattedMonoDer.setEnabled(true);
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JRadioButton jRadioExamenCercana;
	private javax.swing.JRadioButton jRadioExamenLejana;
	private javax.swing.JToggleButton btnGuardar;
	private javax.swing.JCheckBox jCheckBoxBinocular;
	private javax.swing.JCheckBox jCheckBoxMonoDer;
	private javax.swing.JCheckBox jCheckBoxMonoIzq;
	private javax.swing.JFormattedTextField jFormattedLineaBinocular;
	private javax.swing.JFormattedTextField jFormattedMonoDer;
	private javax.swing.JFormattedTextField jFormattedMonoIzq;
	private javax.swing.JFormattedTextField jFormattedLineaMonocularIzqLe;
	private javax.swing.JFormattedTextField jFormattedLineaMonocularDerLe;
	private javax.swing.JFormattedTextField jFormattedLineaBinocularLe;
	
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JRadioButton jRadioBoxBinocular;
	private javax.swing.JRadioButton jRadioBoxMonoDer;
	private javax.swing.JRadioButton jRadioBoxMonoIzq;
	private javax.swing.JLabel lbBinocular;
	private javax.swing.JLabel lbError;
	private javax.swing.JLabel lbMonoDer;
	private javax.swing.JLabel lbMonoIzq;
	private javax.swing.ButtonGroup buttonGroup1;
	private javax.swing.ButtonGroup buttonGroup2;

	@Override
	public void finalizar() {
		// TODO Auto-generated method stub

	}

	@Override
	public void setBtn(JToggleButton btn) {
		this.btn = btn;
	}
	
	// End of variables declaration//GEN-END:variables

}