INSERT INTO APP.PROPIEDAD VALUES ('VALIDAR_LICENCIA','N',null);
INSERT INTO APP.PROPIEDAD VALUES ('LICENCIA_VITALICIA','N',null);
INSERT INTO APP.PROPIEDAD VALUES ('LICENCIA.CANTIDAD.INTENTOS.PERMITIDOS','4',null);
INSERT INTO APP.PROPIEDAD VALUES ('LICENCIA.FECHA.ULTIMO.INTENTO','',null);
INSERT INTO APP.PROPIEDAD VALUES ('LICENCIA.CANTIDAD.INTENTOS','0',null);


INSERT INTO APP.PROPIEDAD VALUES ('PERIODO.PRUEBA.FECHA.INICIO','',null);
INSERT INTO APP.PROPIEDAD VALUES ('LICENCE.LAST.DATE.ACTIVATED','',null);
INSERT INTO APP.PROPIEDAD VALUES ('LICENCE.NRO','',null);
INSERT INTO APP.PROPIEDAD VALUES ('LICENCED','N',null);
INSERT INTO APP.PROPIEDAD VALUES ('PERIODO.PRUEBA.DURACION','45',null);


--LICENCE PROPERTIES

INSERT INTO APP.PROPIEDAD VALUES ('FORMATO.FECHA','dd-MM-yyyy',null);
INSERT INTO APP.PROPIEDAD VALUES ('FORMATO.HORA','HH:mm:ss',null);
INSERT INTO APP.PROPIEDAD VALUES ('FORMATO.FECHA.HORA','dd-MM-yyyy HH:mm:ss',null);
INSERT INTO APP.PROPIEDAD VALUES ('DIRECTORIO.IMAGENES','c:\\',null);
INSERT INTO APP.PROPIEDAD VALUES ('DIRECTORIO.BACKUP.PRIMARIO','D:\\',null);
INSERT INTO APP.PROPIEDAD VALUES ('DIRECTORIO.BACKUP.SECUNDARIO','C:\\',null);
INSERT INTO APP.PROPIEDAD VALUES ('DIRECTORIO.IMAGEN.FONDO.APLICACION','C:\\',null);
INSERT INTO APP.PROPIEDAD VALUES ('DIRECTORIO.IMAGEN.FONDO.SEGUNDO.MONITOR','C:\\',null);
INSERT INTO APP.PROPIEDAD VALUES ('PERSONA.FOTO.REQUERIDA','S',null);
INSERT INTO APP.PROPIEDAD VALUES ('PERSONA.FIRMA.REQUERIDA','N',null);
INSERT INTO APP.PROPIEDAD VALUES ('PERSONA.DNI.MASCARA','##.###.###',null);
INSERT INTO APP.PROPIEDAD VALUES ('PERSONA.DNI.PERMITIR.SOLO.NUMEROS','S',null);
INSERT INTO APP.PROPIEDAD VALUES ('PERSONA.DNI.FIJAR.CANTIDAD.CARACTERES','S',null);
INSERT INTO APP.PROPIEDAD VALUES ('PERSONA.DNI.CANTIDAD.CARACTERES.FIJA','8',null);
INSERT INTO APP.PROPIEDAD VALUES ('SISTEMA.ACTUALIZACION.AUTOMATICA.INICIO','N',null);
INSERT INTO APP.PROPIEDAD VALUES ('SISTEMA.DEVICES.CAMARA','vfw:Microsoft WDM Image Capture (Win32):0',null);
INSERT INTO APP.PROPIEDAD VALUES ('SISTEMA.GUARDAR.LOG.EVENTOS','S',null);
INSERT INTO APP.PROPIEDAD VALUES ('SISTEMA.CONSERVAR.DATOS.LOG.EVENTOS.XDIAS','20',null);
INSERT INTO APP.PROPIEDAD VALUES ('SISTEMA.ORIGEN.FOTOS','DISCO',null);--DISCO WEBCAM EXISTE ENUM
INSERT INTO APP.PROPIEDAD VALUES ('SISTEMA.ORIGEN.FIRMAS','DISCO',null);--DISCO PAD EXISTE ENUM
INSERT INTO APP.PROPIEDAD VALUES ('SISTEMA.IMAGENES.PORCENTAJE.REDUCCION','25',null);
INSERT INTO APP.PROPIEDAD (PROP_CLAVE,PROP_VALOR) VALUES ('SISTEMA.FIRMAS.PORCENTAJE.REDUCCION','20');
INSERT INTO APP.PROPIEDAD (PROP_CLAVE,PROP_VALOR) VALUES ('SISTEMA.BACKUP.AUTOMATICO.ACTIVADO','S');
INSERT INTO APP.PROPIEDAD(PROP_CLAVE,PROP_VALOR)  VALUES ('SISTEMA.BACKUP.AUTOMATICO.CADAXDIAS','20');
INSERT INTO APP.PROPIEDAD (PROP_CLAVE,PROP_VALOR) VALUES ('SISTEMA.BACKUP.SECUNDARIO.SI-NO','N');
INSERT INTO APP.PROPIEDAD (PROP_CLAVE,PROP_VALOR) VALUES ('SISTEMA.BACKUP.FECHAULTIMOBACKUP','28-04-2010');
INSERT INTO APP.PROPIEDAD (PROP_CLAVE,PROP_VALOR) VALUES ('SISTEMA.IMAGEN.PRIMARIA','0');
INSERT INTO APP.PROPIEDAD (PROP_CLAVE,PROP_VALOR) VALUES ('SISTEMA.IMAGEN.SECUNDARIA','0');

INSERT INTO APP.PROPIEDAD(PROP_CLAVE,PROP_VALOR) VALUES ('SISTEMA.FTP_PRINCIPAL_URL','DXTEn5m2NtfIb0JrQ88tOwkSptl3lH87AJZPfePBh80=');
INSERT INTO APP.PROPIEDAD(PROP_CLAVE,PROP_VALOR) VALUES ('SISTEMA.FTP_PRINCIPAL_USER','5WaKymtinfeyUOiInZ0rvp1c1K4M0JAu34k1rvKt5uI=');
INSERT INTO APP.PROPIEDAD(PROP_CLAVE,PROP_VALOR) VALUES ('SISTEMA.FTP_PRINCIPAL_PASSWORD','uLBg40t0YiQ9/9dBV8UgSg==');
INSERT INTO APP.PROPIEDAD(PROP_CLAVE,PROP_VALOR) VALUES ('SISTEMA.FTP_SECUNDARIO_URL','1yT7xdyXFOC1p1EecQ0V3Q==');
INSERT INTO APP.PROPIEDAD(PROP_CLAVE,PROP_VALOR) VALUES ('SISTEMA.FTP_SECUNDARIO_USER','sva1t1RMRadkMMoiRlpKWA==');
INSERT INTO APP.PROPIEDAD(PROP_CLAVE,PROP_VALOR) VALUES ('SISTEMA.FTP_SECUNDARIO_PASSWORD','WXr7F2JirExUiUzOnSAeyA==');


INSERT INTO APP.PROPIEDAD(PROP_CLAVE,PROP_VALOR) VALUES ('SISTEMA.HASH_ULTIMO_ARCHIVO_SCRIPT_EJECUTADO','0');
INSERT INTO APP.PROPIEDAD(PROP_CLAVE,PROP_VALOR) VALUES ('SISTEMA.NOMBRE.PROGRAMA','OpcionesMultiples');
INSERT INTO APP.PROPIEDAD(PROP_CLAVE,PROP_VALOR) VALUES ('SISTEMA.CODIGO_REGION_DESTINO','ar');
INSERT INTO APP.PROPIEDAD(PROP_CLAVE,PROP_VALOR) VALUES ('SISTEMA.VERSION_PRINCIPAL','v1');

--delete from APP.PROPIEDAD where prop_clave = 'EXAMEN.TAMAÑO.PANTALLA.SECUNDARIA.WIDTH';
INSERT INTO APP.PROPIEDAD VALUES ('EXAMEN.TAMAÑO.PANTALLA.SECUNDARIA.HEIGHT','650',null);
INSERT INTO APP.PROPIEDAD VALUES ('EXAMEN.TAMAÑO.PANTALLA.SECUNDARIA.WIDTH','1000',null);
INSERT INTO APP.PROPIEDAD VALUES ('EXAMEN.RESULTADOS.EXAMADO','S',null);--EXAMEN.RESULTADOS.EXAMINADO


insert into app.usuario (USR_NOMBRE,USR_CLAVE,USR_ULTIMO_ACCESO,USR_HABILITADO_SN,DELETED_SN) values('Administrador Sistema','1',null,'S','N');

INSERT INTO APP.PERMISO (PER_CODIGO,PER_DESCRIPCION) VALUES('AM_PERSONA','Registrar/Modificar Persona');
INSERT INTO APP.PERMISO (PER_CODIGO,PER_DESCRIPCION) VALUES('ABM_USR','Puede admistrar usuarios y permisos');
INSERT INTO APP.PERMISO (PER_CODIGO,PER_DESCRIPCION) VALUES('B_PERSONA','Eliminar Persona');
INSERT INTO APP.PERMISO (PER_CODIGO,PER_DESCRIPCION) VALUES('ACCESO_TAREAS_ADM','Puede ingresar a las tareas administrativas');

insert into "APP"."USUARIO_PERMISO"("PER_ID","USR_NOMBRE") values ((select per_id from APP.PERMISO where PER_CODIGO = 'AM_PERSONA'),'Administrador Sistema');
insert into "APP"."USUARIO_PERMISO"("PER_ID","USR_NOMBRE") values ((select per_id from APP.PERMISO where PER_CODIGO = 'ABM_USR'),'Administrador Sistema');
insert into "APP"."USUARIO_PERMISO"("PER_ID","USR_NOMBRE") values ((select per_id from APP.PERMISO where PER_CODIGO = 'B_PERSONA'),'Administrador Sistema');
insert into "APP"."USUARIO_PERMISO"("PER_ID","USR_NOMBRE") values ((select per_id from APP.PERMISO where PER_CODIGO = 'ACCESO_TAREAS_ADM'),'Administrador Sistema');

      
INSERT INTO APP.EXAMEN (EXA_ID,EXA_CODIGO,EXA_NOMBRE,EXA_ORDEN) VALUES(5,'EXA_MP','Examen de opción múltiple',5);

insert into "APP"."USUARIO_EXAMEN"("EXA_ID","USR_NOMBRE") values ((select exa_id from APP.EXAMEN where EXA_CODIGO = 'EXA_MP'),'Administrador Sistema');;


--delete from APP.DOMINIO where dom_clave = 'Categoría Exámen';

INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION) VALUES ('GRAL','Categoría Exámen','Automóbiles Particulares','Automóbiles Particulares','Automóbiles Particulares');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION) VALUES ('GRAL','Categoría Exámen','Remises y Taxis','Remises y Taxis','Remises y Taxis');


INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION) VALUES ('GRAL','Tipo Documento','DNI','DNI','DNI');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION)  VALUES ('GRAL','Tipo Documento','LC','LC','LC');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION)  VALUES ('GRAL','Tipo Documento','PASAPORTE','PASAPORTE','PASAPORTE');

INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION)  VALUES ('GRAL','Sexo','MASCULINO','MASCULINO','M');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION)  VALUES ('GRAL','Sexo','FEMENINO','FEMENINO','F');

INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION)  VALUES ('GRAL','Estado Civil','CASADO','CASADO','CASADO');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION)  VALUES ('GRAL','Estado Civil','SOLTERO','SOLTERO','SOLTERO');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION)  VALUES ('GRAL','Estado Civil','SEPARADO','SEPARADO','SEPARADO');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION)  VALUES ('GRAL','Estado Civil','VIUDO','VIUDO','VIUDO');

INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION)  VALUES ('GRAL','Grupo Sanguíneo','O-','O-','O-');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION)  VALUES ('GRAL','Grupo Sanguíneo','O+','O+','O+');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION)  VALUES ('GRAL','Grupo Sanguíneo','A-','A-','A-');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION)  VALUES ('GRAL','Grupo Sanguíneo','A+','A+','A+');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION)  VALUES ('GRAL','Grupo Sanguíneo','B-','B-','B-');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION)  VALUES ('GRAL','Grupo Sanguíneo','B+','B+','B+');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION)  VALUES ('GRAL','Grupo Sanguíneo','AB-','AB-','AB-');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION)  VALUES ('GRAL','Grupo Sanguíneo','AB+','AB+','AB+');

INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION)  VALUES ('GRAL','Localidad','BERROTARAN','BERROTARAN','BERROTARAN');

INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION)  VALUES ('RESTRICCION','Restricción Visual','Usa Lentes de Contacto','Usa Lentes de Contacto','Usa Lentes de Contacto');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION)  VALUES ('RESTRICCION','Restricción Visual','Operación Ocular','Operación Ocular','Operación Ocular');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION)  VALUES ('RESTRICCION','Restricción Visual','Usa Anteojos','Usa Anteojos','Usa Anteojos');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION)  VALUES ('RESTRICCION','Restricción Visual','Vision Monocular','Vision Monocular','Vision Monocular');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION)  VALUES ('RESTRICCION','Restricción Visual','Estrabismo','Estrabismo','Estrabismo');


INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION)  VALUES ('RESTRICCION','Restricción Auditiva','Operación Auditiva','Operación Auditiva','Operación Auditiva');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION)  VALUES ('RESTRICCION','Restricción Auditiva','Usa Audífonos','Usa Audífonos','Usa Audífonos');

INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION)  VALUES ('RESTRICCION','Restricción Física','Prótesis Superior','Prótesis Superior','Prótesis Superior');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION)  VALUES ('RESTRICCION','Restricción Física','Prótesis Inferior','Prótesis Inferior','Prótesis Inferior');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION) VALUES ('RESTRICCION','Restricción Física','Afección Miembros Superiores','Afección Miembros Superiores','Afección Miembros Superiores');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION) VALUES ('RESTRICCION','Restricción Física','Afección Miembros Inferiores','Afección Miembros Inferiores','Afección Miembros Inferiores');

INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION) VALUES ('IMAGENES','EXTENCION_IMAGENES','png','png','png');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION) VALUES ('IMAGENES','EXTENCION_IMAGENES','jpg','jpg','jpg');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION) VALUES ('IMAGENES','EXTENCION_IMAGENES','jpeg','jpeg','jpeg');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION) VALUES ('IMAGENES','EXTENCION_IMAGENES','gif','gif','gif');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION) VALUES ('IMAGENES','EXTENCION_IMAGENES','tif','tif','tif');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION) VALUES ('IMAGENES','EXTENCION_IMAGENES','tiff','tiff','tiff');


INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION) VALUES ('EXAMEN','EXAMEN_ESTADO','Aprobado','Aprobado','Aprobado');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION) VALUES ('EXAMEN','EXAMEN_ESTADO','Reprobado','Reprobado','Reprobado');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION) VALUES ('EXAMEN','EXAMEN_ESTADO','Derivado','Derivado a Profesional del Área','Derivado a Profesional del Área');


INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION) VALUES ('EXAMEN','TIPO_EXAMEN','Profesional','Profesional','Profesional');
INSERT INTO APP.DOMINIO (DOM_TIPO,DOM_CLAVE,DOM_CODIGO,DOM_VALOR_MOSTRAR,DOM_DESCRIPCION) VALUES ('EXAMEN','TIPO_EXAMEN','Particular','Particular','Particular');

