package ar.com.tecnologiaaplicada.domain;

// Generated 15-ene-2011 15:36:58 by Hibernate Tools 3.4.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Dominio generated by hbm2java
 */
@Entity
@Table(name = "dominio",  uniqueConstraints = @UniqueConstraint(columnNames = {
		"DOM_TIPO", "DOM_CLAVE", "DOM_CODIGO", "DOM_VALOR_MOSTRAR",
		"DOM_DESCRIPCION" }))
public class Dominio implements java.io.Serializable {

	private Long domId;
	private String domTipo;
	private String domClave;
	private String domCodigo;
	private String domValorMostrar;
	private String domDescripcion;

	public Dominio() {
	}

	public Dominio(String domTipo, String domClave, String domCodigo,
			String domValorMostrar, String domDescripcion) {
		this.domTipo = domTipo;
		this.domClave = domClave;
		this.domCodigo = domCodigo;
		this.domValorMostrar = domValorMostrar;
		this.domDescripcion = domDescripcion;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "DOM_ID", unique = true, nullable = false)
	public Long getDomId() {
		return this.domId;
	}

	public void setDomId(Long domId) {
		this.domId = domId;
	}

	@Column(name = "DOM_TIPO", length = 200)
	public String getDomTipo() {
		return this.domTipo;
	}

	public void setDomTipo(String domTipo) {
		this.domTipo = domTipo;
	}

	@Column(name = "DOM_CLAVE", length = 200)
	public String getDomClave() {
		return this.domClave;
	}

	public void setDomClave(String domClave) {
		this.domClave = domClave;
	}

	@Column(name = "DOM_CODIGO", length = 200)
	public String getDomCodigo() {
		return this.domCodigo;
	}

	public void setDomCodigo(String domCodigo) {
		this.domCodigo = domCodigo;
	}

	@Column(name = "DOM_VALOR_MOSTRAR", length = 200)
	public String getDomValorMostrar() {
		return this.domValorMostrar;
	}

	public void setDomValorMostrar(String domValorMostrar) {
		this.domValorMostrar = domValorMostrar;
	}

	@Column(name = "DOM_DESCRIPCION", length = 200)
	public String getDomDescripcion() {
		return this.domDescripcion;
	}

	public void setDomDescripcion(String domDescripcion) {
		this.domDescripcion = domDescripcion;
	}

}
