package ar.com.tecnologiaaplicada.domain;

// Generated 15-ene-2011 15:36:58 by Hibernate Tools 3.4.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ExamenDetalle generated by hbm2java
 */
@Entity
@Table(name = "EXAMEN_DETALLE",  uniqueConstraints = @UniqueConstraint(columnNames = "EXAD_CODIGO"))
public class ExamenDetalle implements java.io.Serializable {

	private Long exadId;
	private Examen examen;
	private String exadDetalle;
	private String exadCodigo;
	private long exadOrden;
	private String exadParametrosCorreccion;
	/*private Set<DetalleLicencia> detalleLicencias = new HashSet<DetalleLicencia>(
			0);*/

	public ExamenDetalle() {
	}

	public ExamenDetalle(Examen examen, String exadDetalle, String exadCodigo,
			long exadOrden) {
		this.examen = examen;
		this.exadDetalle = exadDetalle;
		this.exadCodigo = exadCodigo;
		this.exadOrden = exadOrden;
	}

	public ExamenDetalle(Examen examen, String exadDetalle, String exadCodigo,
			long exadOrden, String exadParametrosCorreccion/*,
			Set<DetalleLicencia> detalleLicencias*/) {
		this.examen = examen;
		this.exadDetalle = exadDetalle;
		this.exadCodigo = exadCodigo;
		this.exadOrden = exadOrden;
		this.exadParametrosCorreccion = exadParametrosCorreccion;
		//this.detalleLicencias = detalleLicencias;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "EXAD_ID", unique = true, nullable = false)
	public Long getExadId() {
		return this.exadId;
	}

	public void setExadId(Long exadId) {
		this.exadId = exadId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EXA_ID", nullable = false)
	public Examen getExamen() {
		return this.examen;
	}

	public void setExamen(Examen examen) {
		this.examen = examen;
	}

	@Column(name = "EXAD_DETALLE", nullable = false, length = 200)
	public String getExadDetalle() {
		return this.exadDetalle;
	}

	public void setExadDetalle(String exadDetalle) {
		this.exadDetalle = exadDetalle;
	}

	@Column(name = "EXAD_CODIGO", unique = true, nullable = false, length = 200)
	public String getExadCodigo() {
		return this.exadCodigo;
	}

	public void setExadCodigo(String exadCodigo) {
		this.exadCodigo = exadCodigo;
	}

	@Column(name = "EXAD_ORDEN", nullable = false)
	public long getExadOrden() {
		return this.exadOrden;
	}

	public void setExadOrden(long exadOrden) {
		this.exadOrden = exadOrden;
	}

	@Column(name = "EXAD_PARAMETROS_CORRECCION", length = 4000)
	public String getExadParametrosCorreccion() {
		return this.exadParametrosCorreccion;
	}

	public void setExadParametrosCorreccion(String exadParametrosCorreccion) {
		this.exadParametrosCorreccion = exadParametrosCorreccion;
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "examenDetalle")
	public Set<DetalleLicencia> getDetalleLicencias() {
		return this.detalleLicencias;
	}

	public void setDetalleLicencias(Set<DetalleLicencia> detalleLicencias) {
		this.detalleLicencias = detalleLicencias;
	}*/

}
