package ar.com.tecnologiaaplicada.domain;

// Generated 15-ene-2011 15:36:58 by Hibernate Tools 3.4.0.Beta1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Collection;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;



/**
 * Licencia generated by hbm2java
 */
@Entity
@Table(name = "LICENCIA", uniqueConstraints = @UniqueConstraint(columnNames = "LIC_NRO"))
public class Licencia implements java.io.Serializable {

	private Long licId;
	private Cliente cliente;
	private String licNro;
	private long licTipo;
	private String licProducto;
	private String licActivaSn;
	private Date licFechaGeneracion;
	private Date licFechaActualizacion;
	private String licDatosAdicionales;
	private Collection<DetalleLicencia> detalleLicencias = new HashSet<DetalleLicencia>(
			0);
	private Collection<Activacion> activacions = new HashSet<Activacion>(0);

	public Licencia() {
	}

	/*public Licencia(Cliente cliente, String licNro, long licTipo,
			long licProducto, String licActivaSn, Date licFechaGeneracion) {
		this.cliente = cliente;
		this.licNro = licNro;
		this.licTipo = licTipo;
		this.licProducto = licProducto;
		this.licActivaSn = licActivaSn;
		this.licFechaGeneracion = licFechaGeneracion;
	}

	public Licencia(Cliente cliente, String licNro, long licTipo,
			long licProducto, String licActivaSn, Date licFechaGeneracion,
			Set<DetalleLicencia> detalleLicencias, Set<Activacion> activacions) {
		this.cliente = cliente;
		this.licNro = licNro;
		this.licTipo = licTipo;
		this.licProducto = licProducto;
		this.licActivaSn = licActivaSn;
		this.licFechaGeneracion = licFechaGeneracion;
		this.detalleLicencias = detalleLicencias;
		this.activacions = activacions;
	}*/

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "LIC_ID", unique = true, nullable = false)
	public Long getLicId() {
		return this.licId;
	}

	public void setLicId(Long licId) {
		this.licId = licId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CLI_ID", nullable = false)
	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	@Column(name = "LIC_NRO", unique = true, nullable = false, length = 200)
	public String getLicNro() {
		return this.licNro;
	}

	public void setLicNro(String licNro) {
		this.licNro = licNro;
	}

	@Column(name = "LIC_TIPO", nullable = false)
	public long getLicTipo() {
		return this.licTipo;
	}

	public void setLicTipo(long licTipo) {
		this.licTipo = licTipo;
	}

	@Column(name = "LIC_PRODUCTO", nullable = false,length = 200)
	public String getLicProducto() {
		return this.licProducto;
	}

	public void setLicProducto(String licProducto) {
		this.licProducto = licProducto;
	}

	@Column(name = "LIC_ACTIVA_SN", nullable = false, length = 1)
	public String getLicActivaSn() {
		return this.licActivaSn;
	}

	public void setLicActivaSn(String licActivaSn) {
		this.licActivaSn = licActivaSn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LIC_FECHA_GENERACION", nullable = false, length = 19)
	public Date getLicFechaGeneracion() {
		return this.licFechaGeneracion;
	}

	public void setLicFechaGeneracion(Date licFechaGeneracion) {
		this.licFechaGeneracion = licFechaGeneracion;
	}

	@Column(name = "LIC_DATOS_ADICIONALES", nullable = true, length = 600)
	public String getLicDatosAdicionales() {
		return licDatosAdicionales;
	}
	
	public void setLicDatosAdicionales(String licDatosAdicionales) {
		this.licDatosAdicionales = licDatosAdicionales;
	}
	//@OneToMany()
	//@Cascade(org.hibernate.annotations.CascadeType.DELETE_ORPHAN)
	
	
	@Transient
	public Collection<DetalleLicencia> getDetalleLicencias() {
		return this.detalleLicencias;
	}

	public void setDetalleLicencias(Collection<DetalleLicencia> detalleLicencias) {
		this.detalleLicencias = detalleLicencias;
	}

	@Transient
	public Collection<Activacion> getActivacions() {
		return this.activacions;
	}

	public void setActivacions(Collection<Activacion> activacions) {
		this.activacions = activacions;
	}
	
	@Transient
	public Date getLicFechaActualizacion() {
		return licFechaActualizacion;
	}
	
	public void setLicFechaActualizacion(Date licFechaActualizacion) {
		this.licFechaActualizacion = licFechaActualizacion;
	}
}
