/*
 * PanelInformesYEstadisticas.java
 *
 * Created on __DATE__, __TIME__
 */

package frontend.paneles;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;

import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.ListSelectionModel;
import javax.swing.JFormattedTextField.AbstractFormatter;
import javax.swing.table.TableColumn;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import frontend.buttons.ButtonBuscar;
import frontend.tablemodel.TableModelPersona;
import frontend.utils.Util;

import testerGeneral.business.ContextManager;
import testerGeneral.domain.Constantes;
import testerGeneral.domain.Dominio;
import testerGeneral.domain.Persona;
import testerGeneral.service.PersonaDefinition;

/**
 * 
 * @author __USER__
 */
public class PanelInformesYEstadisticas extends javax.swing.JPanel {
	private static final Log log = LogFactory.getLog(PanelPersona.class);
	private PersonaDefinition personaService = (PersonaDefinition) ContextManager
			.getBizObject("personaService");

	/** Creates new form PanelInformesYEstadisticas */
	public PanelInformesYEstadisticas() {
		initComponents();
		Util.personaSinResultados(lbSinResultados, true);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		buttonGroupSexo = new javax.swing.ButtonGroup();
		buttonGroupAlcohol = new javax.swing.ButtonGroup();
		buttonGroupPsicofarmacos = new javax.swing.ButtonGroup();
		buttonGroupEstudios = new javax.swing.ButtonGroup();
		jPanelFiltros = new javax.swing.JPanel();
		jTextFieldEdadInicio = new javax.swing.JTextField();
		jLabelEdad2 = new javax.swing.JLabel();
		jTextFieldEdadFin = new javax.swing.JTextField();
		jLabelEdad3 = new javax.swing.JLabel();
		jRadioButtonMasculino = new javax.swing.JRadioButton();
		jRadioButtonFemenino = new javax.swing.JRadioButton();
		btnBuscar = new ButtonBuscar();
		jCheckBoxEdad = new javax.swing.JCheckBox();
		jCheckBoxSexo = new javax.swing.JCheckBox();
		jCheckBoxEstudios = new javax.swing.JCheckBox();
		jCheckBoxTomoHoyAlcohol = new javax.swing.JCheckBox();
		jRadioButtonTomoHoyAlcoholSI = new javax.swing.JRadioButton();
		jRadioButtonTomoHoyAlcoholNO = new javax.swing.JRadioButton();
		jCheckBoxTomoHoyPsicofarmacos = new javax.swing.JCheckBox();
		jRadioButtonTomoHoyPsicofarmacosSI = new javax.swing.JRadioButton();
		jRadioButtonTomoHoyPsicofarmacosNO = new javax.swing.JRadioButton();
		jRadioButtonEstudiosSI = new javax.swing.JRadioButton();
		jRadioButtonEstudiosNO = new javax.swing.JRadioButton();
		jPanelBusqueda = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		tablePersona = new javax.swing.JTable();
		lbSinResultados = new javax.swing.JLabel();

		jPanelFiltros.setBorder(javax.swing.BorderFactory.createTitledBorder(
				null, "Filtros",
				javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
				javax.swing.border.TitledBorder.DEFAULT_POSITION,
				new java.awt.Font("Segoe UI", 3, 12)));

		jTextFieldEdadInicio
				.addFocusListener(new java.awt.event.FocusAdapter() {
					public void focusGained(java.awt.event.FocusEvent evt) {
						jTextFieldEdadInicioFocusGained(evt);
					}
				});

		jLabelEdad2.setText("y");

		jTextFieldEdadFin.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusGained(java.awt.event.FocusEvent evt) {
				jTextFieldEdadFinFocusGained(evt);
			}
		});

		jLabelEdad3.setText("a\u00f1os.");

		buttonGroupSexo.add(jRadioButtonMasculino);
		jRadioButtonMasculino.setText("Masculino");
		jRadioButtonMasculino
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						jRadioButtonMasculinoActionPerformed(evt);
					}
				});

		buttonGroupSexo.add(jRadioButtonFemenino);
		jRadioButtonFemenino.setText("Femenino");
		jRadioButtonFemenino
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						jRadioButtonFemeninoActionPerformed(evt);
					}
				});

		btnBuscar.setToolTipText("Buscar");
		btnBuscar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnBuscarActionPerformed(evt);
			}
		});

		jCheckBoxEdad.setText("Edad: entre");
		jCheckBoxEdad.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jCheckBoxEdadActionPerformed(evt);
			}
		});

		jCheckBoxSexo.setText("Sexo:");
		jCheckBoxSexo.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jCheckBoxSexoActionPerformed(evt);
			}
		});

		jCheckBoxEstudios.setText("Estudios:");
		jCheckBoxEstudios
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						jCheckBoxEstudiosActionPerformed(evt);
					}
				});

		jCheckBoxTomoHoyAlcohol.setText("\u00bfTom\u00f3 hoy alcohol?");
		jCheckBoxTomoHoyAlcohol
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						jCheckBoxTomoHoyAlcoholActionPerformed(evt);
					}
				});

		buttonGroupAlcohol.add(jRadioButtonTomoHoyAlcoholSI);
		jRadioButtonTomoHoyAlcoholSI.setText("Si");
		jRadioButtonTomoHoyAlcoholSI
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						jRadioButtonTomoHoyAlcoholSIActionPerformed(evt);
					}
				});

		buttonGroupAlcohol.add(jRadioButtonTomoHoyAlcoholNO);
		jRadioButtonTomoHoyAlcoholNO.setText("No");
		jRadioButtonTomoHoyAlcoholNO
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						jRadioButtonTomoHoyAlcoholNOActionPerformed(evt);
					}
				});

		jCheckBoxTomoHoyPsicofarmacos
				.setText("\u00bfTom\u00f3 hoy psicof\u00e1rmacos?");
		jCheckBoxTomoHoyPsicofarmacos
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						jCheckBoxTomoHoyPsicofarmacosActionPerformed(evt);
					}
				});

		buttonGroupPsicofarmacos.add(jRadioButtonTomoHoyPsicofarmacosSI);
		jRadioButtonTomoHoyPsicofarmacosSI.setText("Si");
		jRadioButtonTomoHoyPsicofarmacosSI
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						jRadioButtonTomoHoyPsicofarmacosSIActionPerformed(evt);
					}
				});

		buttonGroupPsicofarmacos.add(jRadioButtonTomoHoyPsicofarmacosNO);
		jRadioButtonTomoHoyPsicofarmacosNO.setText("No");
		jRadioButtonTomoHoyPsicofarmacosNO
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						jRadioButtonTomoHoyPsicofarmacosNOActionPerformed(evt);
					}
				});

		buttonGroupEstudios.add(jRadioButtonEstudiosSI);
		jRadioButtonEstudiosSI.setText("Si");
		jRadioButtonEstudiosSI
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						jRadioButtonEstudiosSIActionPerformed(evt);
					}
				});

		buttonGroupEstudios.add(jRadioButtonEstudiosNO);
		jRadioButtonEstudiosNO.setText("No");
		jRadioButtonEstudiosNO
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						jRadioButtonEstudiosNOActionPerformed(evt);
					}
				});

		javax.swing.GroupLayout jPanelFiltrosLayout = new javax.swing.GroupLayout(
				jPanelFiltros);
		jPanelFiltros.setLayout(jPanelFiltrosLayout);
		jPanelFiltrosLayout
				.setHorizontalGroup(jPanelFiltrosLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanelFiltrosLayout
										.createSequentialGroup()
										.addGroup(
												jPanelFiltrosLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanelFiltrosLayout
																		.createSequentialGroup()
																		.addComponent(
																				jCheckBoxSexo)
																		.addGap(
																				18,
																				18,
																				18)
																		.addComponent(
																				jRadioButtonMasculino)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jRadioButtonFemenino))
														.addGroup(
																jPanelFiltrosLayout
																		.createSequentialGroup()
																		.addComponent(
																				jCheckBoxEdad)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jTextFieldEdadInicio,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				30,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jLabelEdad2)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jTextFieldEdadFin,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				33,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jLabelEdad3)))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												92, Short.MAX_VALUE)
										.addComponent(
												btnBuscar,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												48,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap())
						.addGroup(
								jPanelFiltrosLayout.createSequentialGroup()
										.addComponent(jCheckBoxTomoHoyAlcohol)
										.addGap(250, 250, 250))
						.addGroup(
								jPanelFiltrosLayout
										.createSequentialGroup()
										.addGroup(
												jPanelFiltrosLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jCheckBoxTomoHoyPsicofarmacos)
														.addComponent(
																jCheckBoxEstudios))
										.addGap(4, 4, 4)
										.addGroup(
												jPanelFiltrosLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanelFiltrosLayout
																		.createSequentialGroup()
																		.addComponent(
																				jRadioButtonTomoHoyPsicofarmacosSI)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jRadioButtonTomoHoyPsicofarmacosNO))
														.addGroup(
																jPanelFiltrosLayout
																		.createSequentialGroup()
																		.addComponent(
																				jRadioButtonEstudiosSI)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jRadioButtonEstudiosNO))
														.addGroup(
																jPanelFiltrosLayout
																		.createSequentialGroup()
																		.addComponent(
																				jRadioButtonTomoHoyAlcoholSI)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jRadioButtonTomoHoyAlcoholNO)))
										.addGap(58, 58, 58)));
		jPanelFiltrosLayout
				.setVerticalGroup(jPanelFiltrosLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanelFiltrosLayout
										.createSequentialGroup()
										.addGroup(
												jPanelFiltrosLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanelFiltrosLayout
																		.createSequentialGroup()
																		.addGroup(
																				jPanelFiltrosLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jCheckBoxEdad)
																						.addComponent(
																								jLabelEdad2)
																						.addComponent(
																								jTextFieldEdadFin,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jLabelEdad3)
																						.addComponent(
																								jTextFieldEdadInicio,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				jPanelFiltrosLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jCheckBoxSexo)
																						.addComponent(
																								jRadioButtonMasculino)
																						.addComponent(
																								jRadioButtonFemenino))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				jPanelFiltrosLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jRadioButtonEstudiosSI)
																						.addComponent(
																								jRadioButtonEstudiosNO)
																						.addComponent(
																								jCheckBoxEstudios))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addGroup(
																				jPanelFiltrosLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jCheckBoxTomoHoyPsicofarmacos)
																						.addComponent(
																								jRadioButtonTomoHoyPsicofarmacosSI)
																						.addComponent(
																								jRadioButtonTomoHoyPsicofarmacosNO))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addGroup(
																				jPanelFiltrosLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jCheckBoxTomoHoyAlcohol)
																						.addComponent(
																								jRadioButtonTomoHoyAlcoholSI)
																						.addComponent(
																								jRadioButtonTomoHoyAlcoholNO)))
														.addComponent(
																btnBuscar,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																48,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap(11, Short.MAX_VALUE)));

		((ButtonBuscar) btnBuscar).init();

		jPanelBusqueda.setBorder(javax.swing.BorderFactory.createTitledBorder(
				null, Constantes.PANEL_RESULTADOS_BUSQUEDA,
				javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
				javax.swing.border.TitledBorder.DEFAULT_POSITION,
				new java.awt.Font("Segoe UI", 3, 12)));
		jPanelBusqueda.setFocusable(false);

		tablePersona.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] {

				}, new String[] {

				}));
		tablePersona.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				tablePersonaMouseClicked(evt);
			}
		});
		jScrollPane1.setViewportView(tablePersona);

		lbSinResultados.setForeground(new java.awt.Color(204, 0, 0));
		lbSinResultados.setIcon(new ImageIcon(getClass().getResource(
				Constantes.IMG_ERROR)));
		lbSinResultados.setText("No se encontraron coincidencias");

		javax.swing.GroupLayout jPanelBusquedaLayout = new javax.swing.GroupLayout(
				jPanelBusqueda);
		jPanelBusqueda.setLayout(jPanelBusquedaLayout);
		jPanelBusquedaLayout
				.setHorizontalGroup(jPanelBusquedaLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanelBusquedaLayout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanelBusquedaLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jScrollPane1,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																335,
																Short.MAX_VALUE)
														.addComponent(
																lbSinResultados,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																335,
																Short.MAX_VALUE))));
		jPanelBusquedaLayout
				.setVerticalGroup(jPanelBusquedaLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanelBusquedaLayout
										.createSequentialGroup()
										.addComponent(
												jScrollPane1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												318,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												lbSinResultados,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												24,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup().addComponent(jPanelFiltros,
						javax.swing.GroupLayout.PREFERRED_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.PREFERRED_SIZE).addGap(6, 6, 6)
						.addComponent(jPanelBusqueda,
								javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jPanelFiltros,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jPanelBusqueda,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap(26, Short.MAX_VALUE)));
	}// </editor-fold>
	//GEN-END:initComponents

	private void jRadioButtonEstudiosSIActionPerformed(
			java.awt.event.ActionEvent evt) {
		jCheckBoxEstudios.setSelected(true);
	}

	private void jRadioButtonEstudiosNOActionPerformed(
			java.awt.event.ActionEvent evt) {
		jCheckBoxEstudios.setSelected(true);
	}

	private void jCheckBoxTomoHoyAlcoholActionPerformed(
			java.awt.event.ActionEvent evt) {
		if (!jCheckBoxTomoHoyAlcohol.isSelected()) {
			buttonGroupAlcohol.clearSelection();
		} else {
			jRadioButtonTomoHoyAlcoholNO.setSelected(true);
		}
	}

	private void jCheckBoxTomoHoyPsicofarmacosActionPerformed(
			java.awt.event.ActionEvent evt) {
		if (!jCheckBoxTomoHoyPsicofarmacos.isSelected()) {
			buttonGroupPsicofarmacos.clearSelection();
		} else {
			jRadioButtonTomoHoyPsicofarmacosNO.setSelected(true);
		}
	}

	private void jRadioButtonTomoHoyAlcoholNOActionPerformed(
			java.awt.event.ActionEvent evt) {
		jCheckBoxTomoHoyAlcohol.setSelected(true);
	}

	private void jRadioButtonTomoHoyAlcoholSIActionPerformed(
			java.awt.event.ActionEvent evt) {
		jCheckBoxTomoHoyAlcohol.setSelected(true);
	}

	private void jRadioButtonTomoHoyPsicofarmacosNOActionPerformed(
			java.awt.event.ActionEvent evt) {
		jCheckBoxTomoHoyPsicofarmacos.setSelected(true);
	}

	private void jRadioButtonTomoHoyPsicofarmacosSIActionPerformed(
			java.awt.event.ActionEvent evt) {
		jCheckBoxTomoHoyPsicofarmacos.setSelected(true);
	}

	private void jCheckBoxEstudiosActionPerformed(java.awt.event.ActionEvent evt) {
		if (!jCheckBoxEstudios.isSelected()) {
			buttonGroupEstudios.clearSelection();
		} else {
			jRadioButtonEstudiosNO.setSelected(true);
		}
	}

	private void jCheckBoxSexoActionPerformed(java.awt.event.ActionEvent evt) {
		if (!jCheckBoxSexo.isSelected()) {
			buttonGroupSexo.clearSelection();
		} else {
			jRadioButtonMasculino.setSelected(true);
		}
	}

	private void jRadioButtonFemeninoActionPerformed(
			java.awt.event.ActionEvent evt) {
		jCheckBoxSexo.setSelected(true);
	}

	private void jRadioButtonMasculinoActionPerformed(
			java.awt.event.ActionEvent evt) {
		jCheckBoxSexo.setSelected(true);
	}

	private void jTextFieldEdadFinFocusGained(java.awt.event.FocusEvent evt) {
		jCheckBoxEdad.setSelected(true);
	}

	private void jCheckBoxEdadActionPerformed(java.awt.event.ActionEvent evt) {
		if (jCheckBoxEdad.isSelected()) {
			jTextFieldEdadInicio.setEnabled(true);
			jTextFieldEdadFin.setEnabled(true);
		} else {
			jTextFieldEdadInicio.setEnabled(false);
			jTextFieldEdadFin.setEnabled(false);
		}
	}

	private void jTextFieldEdadInicioFocusGained(java.awt.event.FocusEvent evt) {
		jCheckBoxEdad.setSelected(true);
	}

	private void tablePersonaMouseClicked(java.awt.event.MouseEvent evt) {
		// seleccionarPersona();
	}

	private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {
		cargarPersonas();

	}

	@SuppressWarnings("unchecked")
	public void cargarPersonas() {
		log.info("cargarPersonas");

		boolean error = false;
		setTableModel(new ArrayList());
		Calendar fechaInicio = Calendar.getInstance();
		Calendar fechaFin = Calendar.getInstance();

		try {
			Util.personaSinResultados(lbSinResultados, true);
			Persona per = new Persona();

			/*
			 * Filtro de edad.
			 */
			if (jCheckBoxEdad.isSelected()) {

				if (!jTextFieldEdadInicio.getText().isEmpty()
						&& !jTextFieldEdadFin.getText().isEmpty()) {

					Calendar hoy = Calendar.getInstance();
					hoy.add(Calendar.YEAR, -Integer
							.valueOf(jTextFieldEdadInicio.getText()));
					fechaInicio = hoy;

					hoy = Calendar.getInstance();
					hoy.add(Calendar.YEAR, -Integer.valueOf(jTextFieldEdadFin
							.getText()) - 1);

					fechaFin = hoy;

					System.out.println(fechaInicio);
					System.out.println(fechaFin);

				} else {
					jCheckBoxEdad.setSelected(false);
				}
			}

			/*
			 * Filtro de estudios.
			 */
			if (jCheckBoxEstudios.isSelected()) {
				if (jRadioButtonEstudiosSI.isSelected()) {
					per.setPerEstudios("SI");
				}
				if (jRadioButtonEstudiosNO.isSelected()) {
					per.setPerEstudios("NO");
				}

			}

			/*
			 * Filtro de sexo.
			 */
			if (jCheckBoxSexo.isSelected()) {

				if (jRadioButtonMasculino.isSelected()) {
					per.setPerSexo("MASCULINO");
				}
				if (jRadioButtonFemenino.isSelected()) {
					per.setPerSexo("FEMENINO");
				}

			}

			/*
			 * Filtro de Tomó hoy alcohol.
			 */
			if (jCheckBoxTomoHoyAlcohol.isSelected()) {

				if (jRadioButtonTomoHoyAlcoholSI.isSelected()) {
					per.setPerTomoHoyAlcohol("1");
				}
				if (jRadioButtonTomoHoyAlcoholNO.isSelected()) {
					per.setPerTomoHoyAlcohol("2");
				}

			}

			/*
			 * Filtro de Tomó hoy psicofármacos.
			 */
			if (jCheckBoxTomoHoyPsicofarmacos.isSelected()) {

				if (jRadioButtonTomoHoyPsicofarmacosSI.isSelected()) {
					per.setPerTomoHoyPsicofarmacosSN("1");
				}
				if (jRadioButtonTomoHoyPsicofarmacosNO.isSelected()) {
					per.setPerTomoHoyPsicofarmacosSN("2");
				}

			}

			List<Persona> personas;
			if (jCheckBoxEdad.isSelected()) {
				personas = personaService.getAll(per, fechaFin.getTime(),
						fechaInicio.getTime());
			} else {
				personas = personaService.getAll(per);
			}

			if (!error) {
				setTableModel(personas);
			}

		} catch (Exception e) {
			throw new RuntimeException(e);
		}
	}

	public void setTableModel(List lst) {
		TableModelPersona tableModel = new TableModelPersona();
		tableModel.setLst(lst);
		tablePersona.setModel(tableModel);
		tablePersona.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
		tablePersona.setAutoCreateRowSorter(false);

		TableColumn column = tablePersona.getColumnModel().getColumn(1);
		column.setPreferredWidth(20);
		column.setWidth(20);
		column.setMinWidth(20);

		if (lst.size() == 0)
			Util.personaSinResultados(lbSinResultados, false);
		else
			tablePersona.setAutoCreateRowSorter(true);
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton btnBuscar;
	private javax.swing.ButtonGroup buttonGroupAlcohol;
	private javax.swing.ButtonGroup buttonGroupEstudios;
	private javax.swing.ButtonGroup buttonGroupPsicofarmacos;
	private javax.swing.ButtonGroup buttonGroupSexo;
	private javax.swing.JCheckBox jCheckBoxEdad;
	private javax.swing.JCheckBox jCheckBoxEstudios;
	private javax.swing.JCheckBox jCheckBoxSexo;
	private javax.swing.JCheckBox jCheckBoxTomoHoyAlcohol;
	private javax.swing.JCheckBox jCheckBoxTomoHoyPsicofarmacos;
	private javax.swing.JLabel jLabelEdad2;
	private javax.swing.JLabel jLabelEdad3;
	private javax.swing.JPanel jPanelBusqueda;
	private javax.swing.JPanel jPanelFiltros;
	private javax.swing.JRadioButton jRadioButtonEstudiosNO;
	private javax.swing.JRadioButton jRadioButtonEstudiosSI;
	private javax.swing.JRadioButton jRadioButtonFemenino;
	private javax.swing.JRadioButton jRadioButtonMasculino;
	private javax.swing.JRadioButton jRadioButtonTomoHoyAlcoholNO;
	private javax.swing.JRadioButton jRadioButtonTomoHoyAlcoholSI;
	private javax.swing.JRadioButton jRadioButtonTomoHoyPsicofarmacosNO;
	private javax.swing.JRadioButton jRadioButtonTomoHoyPsicofarmacosSI;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextField jTextFieldEdadFin;
	private javax.swing.JTextField jTextFieldEdadInicio;
	private javax.swing.JLabel lbSinResultados;
	private javax.swing.JTable tablePersona;
	// End of variables declaration//GEN-END:variables

}