/*
 * PanelLogEventos.java
 *
 * Created on __DATE__, __TIME__
 */

package frontend.paneles;

import java.awt.Component;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.Date;
import java.util.List;
import java.util.Vector;

import javax.swing.ImageIcon;
import javax.swing.JFormattedTextField;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.JFormattedTextField.AbstractFormatter;
import javax.swing.table.TableColumn;
import javax.swing.table.TableRowSorter;
import javax.swing.text.MaskFormatter;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import testerGeneral.business.ContextManager;
import testerGeneral.comparetors.DateComparator;
import testerGeneral.domain.Auditoria;
import testerGeneral.domain.Constantes;
import testerGeneral.domain.UsuarioCommon;
import testerGeneral.focus.MyOwnFocusTraversalPolicy;
import testerGeneral.service.AuditoriaDefinition;
import testerGeneral.service.UsuarioDefinition;
import frontend.buttons.ButtonBuscar;
import frontend.tablemodel.TableModelAuditoria;
import frontend.utils.Util;

/**
 *
 * @author  __USER__
 */
public class PanelLogEventos extends javax.swing.JPanel {

	private static final Log log = LogFactory.getLog(PanelLogEventos.class);
	private UsuarioDefinition usuarioService = (UsuarioDefinition) ContextManager
			.getBizObject("usuarioService");
	private UsuarioCommon usr;

	/** Creates new form PanelLogEventos */
	public PanelLogEventos(UsuarioCommon usr) {
		this.usr = usr;
		initComponents();

		ocultarSinResultados(true);
		cargarUsuarios();

		TableModelAuditoria tableModel = new TableModelAuditoria();
		tableModel.setLst(new ArrayList());
		tableAud.setModel(tableModel);
		tableAud.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
		tableAud.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);

		Vector<Component> order = new Vector<Component>();
		order.add(dateDesde);//1
		order.add(dateHasta);//2
		order.add(cbUsuarios);//3
		order.add(txtBusquedaEstacion);//4
		order.add(btnBuscar);//5
		order.add(tableAud);//6
		MyOwnFocusTraversalPolicy newPolicy = new MyOwnFocusTraversalPolicy(
				order);

		String mascaraMostrar = formatoFecha.replaceAll("y", "A");
		mascaraMostrar = mascaraMostrar.replaceAll("M", "M");
		mascaraMostrar = mascaraMostrar.replaceAll("d", "D");
		lbFechaEjemplo.setText(mascaraMostrar);

		this.setFocusTraversalPolicy(newPolicy);
		valorPorDefectoFecha = dateDesde.getText();

	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel3 = new javax.swing.JPanel();
		btnBuscar = new ButtonBuscar();
		jLabel4 = new javax.swing.JLabel();
		txtBusquedaEstacion = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();
		cbUsuarios = new javax.swing.JComboBox();
		dateHasta = setFecha();
		dateDesde = setFecha();
		lbFechaEjemplo = new javax.swing.JLabel();
		jPanel1 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		tableAud = new javax.swing.JTable();
		lbSinResultados = new javax.swing.JLabel();

		setFocusCycleRoot(true);

		jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null,
				Constantes.PANEL_FILTROS_BUSQUEDA,
				javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
				javax.swing.border.TitledBorder.DEFAULT_POSITION,
				new java.awt.Font("Segoe UI", 3, 12)));

		btnBuscar.setToolTipText("Buscar");
		btnBuscar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnBuscarActionPerformed(evt);
			}
		});

		jLabel4.setText(Constantes.LB_ESTACION);

		txtBusquedaEstacion
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						txtBusquedaEstacionActionPerformed(evt);
					}
				});

		jLabel5.setText(Constantes.LB_EVENTOS);

		jLabel6.setText("y");

		jLabel1.setText(Constantes.LB_USUARIO);

		cbUsuarios.setMaximumSize(new java.awt.Dimension(0, 0));
		cbUsuarios.setPreferredSize(new java.awt.Dimension(0, 0));

		lbFechaEjemplo.setFont(new java.awt.Font("Segoe UI", 0, 11));
		lbFechaEjemplo.setText("jLabel17");

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(
				jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout
				.setHorizontalGroup(jPanel3Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel3Layout
										.createSequentialGroup()
										.addGap(5, 5, 5)
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel3Layout
																		.createSequentialGroup()
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				jPanel3Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jLabel5,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								125,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jLabel1)))
														.addComponent(jLabel4))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																txtBusquedaEstacion,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																237,
																Short.MAX_VALUE)
														.addGroup(
																jPanel3Layout
																		.createSequentialGroup()
																		.addComponent(
																				dateDesde,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				81,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addComponent(
																				jLabel6,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				12,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				dateHasta,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				74,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				lbFechaEjemplo,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				48,
																				Short.MAX_VALUE))
														.addComponent(
																cbUsuarios, 0,
																237,
																Short.MAX_VALUE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												btnBuscar,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												48,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(454, 454, 454)));
		jPanel3Layout
				.setVerticalGroup(jPanel3Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel3Layout
										.createSequentialGroup()
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel3Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel3Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jLabel5,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								Short.MAX_VALUE)
																						.addComponent(
																								jLabel6)
																						.addComponent(
																								dateDesde,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								dateHasta,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								lbFechaEjemplo))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				jPanel3Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jLabel1)
																						.addComponent(
																								cbUsuarios,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								20,
																								Short.MAX_VALUE))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				jPanel3Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jLabel4)
																						.addComponent(
																								txtBusquedaEstacion,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE)))
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																jPanel3Layout
																		.createSequentialGroup()
																		.addContainerGap(
																				28,
																				Short.MAX_VALUE)
																		.addComponent(
																				btnBuscar,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				48,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addContainerGap()));

		((ButtonBuscar) btnBuscar).init();

		jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null,
				Constantes.PANEL_RESULTADOS_BUSQUEDA,
				javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
				javax.swing.border.TitledBorder.DEFAULT_POSITION,
				new java.awt.Font("Segoe UI", 3, 12)));

		tableAud.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { "fsager", "No" }, { "vpaolini", "Si" },
						{ "jtesta", "Si" }, { null, null } }, new String[] {
						"Nombre usuario", "Habilitado" }) {
			Class[] types = new Class[] { java.lang.String.class,
					java.lang.String.class };
			boolean[] canEdit = new boolean[] { false, false };

			public Class getColumnClass(int columnIndex) {
				return types[columnIndex];
			}

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
		jScrollPane1.setViewportView(tableAud);

		lbSinResultados.setForeground(new java.awt.Color(204, 0, 0));
		lbSinResultados.setIcon(new ImageIcon(getClass().getResource(
				Constantes.IMG_ERROR)));
		lbSinResultados.setText(Constantes.ERROR_SIN_RESULTADOS);

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																jScrollPane1,
																javax.swing.GroupLayout.Alignment.LEADING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																857,
																Short.MAX_VALUE)
														.addComponent(
																lbSinResultados,
																javax.swing.GroupLayout.Alignment.LEADING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																857,
																Short.MAX_VALUE))
										.addContainerGap()));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(
												jScrollPane1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												322,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												lbSinResultados,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												24,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																jPanel1,
																javax.swing.GroupLayout.Alignment.LEADING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																jPanel3,
																javax.swing.GroupLayout.Alignment.LEADING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE))
										.addContainerGap()));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(
												jPanel3,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jPanel1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));
	}// </editor-fold>
	//GEN-END:initComponents

	private void txtBusquedaEstacionActionPerformed(
			java.awt.event.ActionEvent evt) {
		cargarAuditoria();
	}

	private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {
		cargarAuditoria();
	}

	public void cargarAuditoria() {
		try {
			log.info("cargarAuditoria");

			ocultarSinResultados(true);
			Auditoria aud = new Auditoria();
			UsuarioCommon usu = (UsuarioCommon) cbUsuarios.getSelectedItem();
			aud.setAudUsuario(usu.getUsrNombre());
			aud.setAudEstacion(txtBusquedaEstacion.getText() + "%");

			AuditoriaDefinition auditoriaService = (AuditoriaDefinition) ContextManager
					.getBizObject("auditoriaService");

			List<Auditoria> auditorias = auditoriaService.getAll(aud,
					getFecha(dateDesde), getFecha(dateHasta));

			TableModelAuditoria tableModel = new TableModelAuditoria();
			tableModel.setLst(auditorias);
			tableAud.setModel(tableModel);
			tableAud.setRowSorter(null);

			TableColumn column = tableAud.getColumnModel().getColumn(4);
			column.setPreferredWidth(200);
			column.setWidth(200);
			column.setMinWidth(200);

			if (auditorias.size() == 0)
				ocultarSinResultados(false);
			else {
				TableRowSorter sorter = new TableRowSorter(tableModel);
				sorter.setComparator(0, com);
				tableAud.setRowSorter(sorter);
			}

		} catch (Exception e) {
			log.error(e.getMessage(), e);
			throw new RuntimeException(e);
		}
	}

	public Date getFecha(JFormattedTextField txtDate) {
		if (valorPorDefectoFecha.compareTo(txtDate.getText()) != 0) {
			AbstractFormatter formatter = txtDate.getFormatter();
			if (formatter != null) {
				String text = txtDate.getText();
				try {
					formatter.stringToValue(text);

					sdf.setLenient(false);

					Date hoy = new Date();
					Util.redondearFecha(hoy);

					Date fecha = sdf.parse(txtDate.getText());

					return fecha;
				} catch (ParseException pe) {
					Util.mostrarError(lbSinResultados,
							Constantes.ERROR_PER_FECHA_SINFORMATO, false);
				}
			}
		}

		return null;
	}

	public void ocultarSinResultados(boolean ocultar) {
		log.info("ocultarSinResultados");

		if (ocultar) {
			lbSinResultados.setText("");
			lbSinResultados.setIcon(null);
		} else {
			lbSinResultados.setIcon(new ImageIcon(getClass().getResource(
					Constantes.IMG_ERROR)));
			lbSinResultados.setText(Constantes.ERROR_SIN_RESULTADOS);
		}

	}

	private void cargarUsuarios() {
		try {
			usr.setDeletedSn(null);
			usr.setUsrHabilitadoSn("S");

			List<UsuarioCommon> usuarios;

			cbUsuarios.addItem(new UsuarioCommon());
			usuarios = usuarioService.getAll(usr);
			for (int i = 0; i < usuarios.size(); i++) {
				cbUsuarios.addItem(usuarios.get(i));
			}

		} catch (Exception e) {

			log.error(e.getMessage(), e);
			throw new RuntimeException(e);
		}

	}

	public JFormattedTextField setFecha() {
		try {
			String mascara = formatoFecha.replaceAll("y", "#");
			mascara = mascara.replaceAll("M", "#");
			mascara = mascara.replaceAll("d", "#");
			JFormattedTextField textField = new javax.swing.JFormattedTextField(
					new MaskFormatter(mascara));
			textField.setFocusLostBehavior(JFormattedTextField.COMMIT);

			return textField;
		} catch (ParseException e) {
			throw new RuntimeException(e);
		}

	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton btnBuscar;
	private javax.swing.JComboBox cbUsuarios;
	private javax.swing.JFormattedTextField dateDesde;
	private javax.swing.JFormattedTextField dateHasta;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JLabel lbFechaEjemplo;
	private javax.swing.JLabel lbSinResultados;
	private javax.swing.JTable tableAud;
	private javax.swing.JTextField txtBusquedaEstacion;
	// End of variables declaration//GEN-END:variables
	private String formatoFechaHora = ContextManager
			.getProperty("FORMATO.FECHA.HORA");
	private String formatoFecha = ContextManager.getProperty("FORMATO.FECHA");
	private String valorPorDefectoFecha;
	private SimpleDateFormat sdf = new SimpleDateFormat(formatoFecha);
	private SimpleDateFormat sdfHora = new SimpleDateFormat(formatoFechaHora);

	private DateComparator com = new DateComparator();

}