/*
 * PanelFinalizarExamen.java
 *
 * Created on __DATE__, __TIME__
 */

package frontend.paneles.examenes;

import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

import testerGeneral.business.ContextManager;
import testerGeneral.domain.Constantes;
import testerGeneral.domain.Examen;
import testerGeneral.domain.ExamenDetalle;
import testerGeneral.domain.PersonaExamen;
import testerGeneral.domain.ResultadoDetalleExamen;
import testerGeneral.service.ExamenDetalleDefinition;
import testerGeneral.service.PersonaExamenDefinition;
import testerGeneral.service.ResultadoDetalleExamenDefinition;
import frontend.buttons.ButtonCancelarMini;
import frontend.buttons.ButtonExaminar;
import frontend.buttons.ButtonGuardar;
import frontend.components.JOptionPaneTesterGral;
import frontend.paneles.PanelMenuPrincipal;
import frontend.tablemodel.RowRenderer;
import frontend.tablemodel.TableModelResultadoExamen;
import frontend.utils.Util;
import frontend.ventanas.DialogoTomarExamen;
import frontend.ventanas.VentanaReportes;

/**
 *
 * @author  __USER__
 */
public class PanelFinalizarExamen extends javax.swing.JPanel {

	/** Creates new form PanelFinalizarExamen */
	public PanelFinalizarExamen(PersonaExamen perExamen) {
		this.perExamen = perExamen;
		initComponents();
		Util.cargarDominios(cbEstado, Constantes.ESTADO_EXAMEN, false);
		detalleExamen();
		setTableModel(lstResultadoDetalleExamen);
	}

	public void detalleExamen() {
		try {
			ExamenDetalle detallesExamenen = new ExamenDetalle();
			detallesExamenen.setExamen(perExamen.getExamen());
			ExamenDetalleDefinition examenDetalleService = (ExamenDetalleDefinition) ContextManager
					.getBizObject("examenDetalleService");

			List<ExamenDetalle> detallesExamenes = examenDetalleService
					.getAll(detallesExamenen);

			for (int i = 0; i < detallesExamenes.size(); i++) {

				ResultadoDetalleExamen example = new ResultadoDetalleExamen();
				example.setExamenDetalle(detallesExamenes.get(i));
				example.setPersonaExamen(perExamen);
				List<ResultadoDetalleExamen> lstResultados = resultadoDetalleExamenService
						.getAll(example);

				if (lstResultados.size() < 1) {
					ResultadoDetalleExamen resultadoDetalleExamen = new ResultadoDetalleExamen();
					resultadoDetalleExamen.setExamenDetalle(detallesExamenes
							.get(i));
					lstResultadoDetalleExamen.add(resultadoDetalleExamen);
				} else {
					lstResultadoDetalleExamen.add(lstResultados.get(0));
				}
			}

		} catch (Exception e) {
			throw new RuntimeException(e);
		}
	}

	public void setTableModel(List lst) {
		TableModelResultadoExamen tableModel = new TableModelResultadoExamen(
				perExamen.getExamen().getExaCodigo());

		tableModel.setLst(lst);
		tableDetalleExamen.setModel(tableModel);
		tableDetalleExamen
				.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
		tableDetalleExamen.setAutoCreateRowSorter(true);
        for(int j = 0; j < tableModel.getColumnCount(); j++)
        	tableDetalleExamen.getColumnModel().getColumn(j).setCellRenderer(new RowRenderer());
        
        for(int i=0;i<tableModel.getLstUsuario().size();i++)
        {
        	tableDetalleExamen.setRowHeight(i,100);
        }
        
		if (perExamen.getExamen().getExaCodigo().equals(
				Examen.EXA_CODIGO_VISION)) {
			tableDetalleExamen.setRowHeight(0, 50);
			
			/*DefaultTableCellRenderer renderer =new DefaultTableCellRenderer();
			renderer.setToolTipText(ParametrosCorreccion.parametro);
			tableDetalleExamen.getColumnModel().getColumn(2).setCellRenderer(renderer);*/

	        
	        //tableModel.get
			
			
			tableDetalleExamen.setRowHeight(1, 50);
			tableDetalleExamen.setRowHeight(3, 60);
			tableDetalleExamen.setRowHeight(4, 50);
			tableDetalleExamen.setRowHeight(8, 130);
			tableDetalleExamen.setRowHeight(9,80);
		}
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		tableDetalleExamen = new javax.swing.JTable();
		cbEstado = new javax.swing.JComboBox();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		btnGuardar = new ButtonGuardar();
		btnExaminar = new ButtonExaminar();
		btnCancelarFoto = new ButtonCancelarMini();
		lbAdjunto = new javax.swing.JLabel();

		jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null,
				"Detalle Exámen",
				javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
				javax.swing.border.TitledBorder.DEFAULT_POSITION,
				new java.awt.Font("Segoe UI", 3, 12)));
		jPanel1.setFocusable(false);

		tableDetalleExamen.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { "fsager", "No" }, { "vpaolini", "Si" },
						{ "jtesta", "Si" }, { null, null } }, new String[] {
						"Nombre usuario", "Habilitado" }) {
			Class[] types = new Class[] { java.lang.String.class,
					java.lang.String.class };
			boolean[] canEdit = new boolean[] { false, false };

			public Class getColumnClass(int columnIndex) {
				return types[columnIndex];
			}

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
		jScrollPane1.setViewportView(tableDetalleExamen);

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel1Layout.createSequentialGroup().addContainerGap()
						.addComponent(jScrollPane1,
								javax.swing.GroupLayout.DEFAULT_SIZE, 525,
								Short.MAX_VALUE).addContainerGap()));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel1Layout.createSequentialGroup().addComponent(
						jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE,
						305, Short.MAX_VALUE).addContainerGap()));

		cbEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"Item 1", "Item 2", "Item 3", "Item 4" }));

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18));
		jLabel1.setText("Resultado General del Examen:");

		jLabel2.setText("Adjuntar Documentacion:");

		btnGuardar.setText("Guardar");
		btnGuardar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnGuardarActionPerformed(evt);
			}
		});

		btnExaminar.setIcon(new ImageIcon(getClass().getResource(
				"/images/agregar.png")));
		btnExaminar.setToolTipText("Examinar");
		((ButtonExaminar) btnExaminar).init();
		btnExaminar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnExaminarActionPerformed(evt);
			}
		});

		btnCancelarFoto.setIcon(new ImageIcon(getClass().getResource(
				"/images/agregar.png")));
		btnCancelarFoto.setToolTipText("Examinar");
		((ButtonCancelarMini) btnCancelarFoto).init();
		btnCancelarFoto.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnCancelarFotoActionPerformed(evt);
			}
		});

		lbAdjunto.setFont(new java.awt.Font("Segoe UI", 3, 14));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								layout
										.createSequentialGroup()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																jPanel1,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addContainerGap()
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								false)
																						.addGroup(
																								layout
																										.createSequentialGroup()
																										.addComponent(
																												jLabel2)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												btnExaminar,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												70,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												Short.MAX_VALUE)
																										.addComponent(
																												btnCancelarFoto,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												70,
																												javax.swing.GroupLayout.PREFERRED_SIZE))
																						.addComponent(
																								jLabel1))
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								layout
																										.createSequentialGroup()
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												cbEstado,
																												0,
																												253,
																												Short.MAX_VALUE))
																						.addGroup(
																								layout
																										.createSequentialGroup()
																										.addGap(
																												7,
																												7,
																												7)
																										.addComponent(
																												lbAdjunto,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												253,
																												Short.MAX_VALUE))))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addContainerGap(
																				481,
																				Short.MAX_VALUE)
																		.addComponent(
																				btnGuardar,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				80,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addContainerGap()));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(
												jPanel1,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																false)
														.addComponent(jLabel2)
														.addComponent(
																btnExaminar,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																25,
																Short.MAX_VALUE)
														.addComponent(
																btnCancelarFoto,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																25,
																Short.MAX_VALUE)
														.addComponent(
																lbAdjunto,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																17,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(11, 11, 11)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel1)
														.addComponent(
																cbEstado,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(24, 24, 24)
										.addComponent(
												btnGuardar,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												20,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap()));

		((ButtonGuardar) btnGuardar).init();
	}// </editor-fold>
	//GEN-END:initComponents

	private void btnCancelarFotoActionPerformed(java.awt.event.ActionEvent evt) {
		lbAdjunto.setText(null);
		perExamen.setPexaAdj(new byte[1]);
		perExamen.setPexaNombreAdjunto(null);
	}

	private void btnExaminarActionPerformed(java.awt.event.ActionEvent evt) {
		try
		{
			String dirDoc="tmpDocs";
			String dirArchivo=System.getProperty("user.dir")+File.separator+dirDoc+File.separator;
			
			SimpleDateFormat sdf=new SimpleDateFormat("dd-MM-yyyy"); 
			String fileName=System.currentTimeMillis()+".doc";
			String file=dirArchivo;
			File f=new File(file);
			f.mkdir();
			file=dirArchivo+fileName;
			f=new File(file);
			f.createNewFile();
			
			//C:\\Program Files (x86)\\Microsoft Office\\Office12\\WINWORD.EXE
			String application="WINWORD.EXE ";
			Process p = Runtime.getRuntime().exec(
					application+"\""+ file+"\"");
			Util.minimizar(Util.framePrincipal);
			p.waitFor();
			
			Thread.sleep(1000);
			
			File renameTo=new File(dirArchivo+System.currentTimeMillis()+".doc");
			while(!f.renameTo(renameTo))
			{
				Thread.sleep(100);
			}
			
			byte[] bytes = testerGeneral.persistence.impl.Util.getBytesFromFile(renameTo.getAbsolutePath());
			perExamen.setPexaNombreAdjunto(perExamen.getPersona().getPerNumeroDoc()+" "+sdf.format(new Date())+".doc");
			perExamen.setPexaAdj(bytes);
			lbAdjunto.setText(perExamen.getPexaNombreAdjunto());
			renameTo.delete();
			JOptionPaneTesterGral.showInternalMessageDialog(
					"Documentación Adjuntada Correctamente", "Adjuntar",
					JOptionPane.INFORMATION_MESSAGE);
			
		} catch (Exception e) {
			throw new RuntimeException(e);
		}
	}

	private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {

		try {
			perExamen.setPexaEstado(Examen.ESTADO_FIN);
			perExamen.setPexaResultadoMedico(cbEstado.getSelectedItem()
					.toString());
			personaExamenService.update(perExamen);

			imprimirResultado();

			int op = JOptionPaneTesterGral.showInternal("<HTML>"+Constantes.MENSAJE_GUARDADO+"<BR>¿Desea continuar tomando exámenes?</HTML>",
					Constantes.MENSAJE_GUARDADO_TIT, JOptionPane.QUESTION_MESSAGE);

			if (op == JOptionPane.YES_OPTION) {
				
				final DialogoTomarExamen dialogoTomarExamen = new DialogoTomarExamen(perExamen.getPersona(),(PanelMenuPrincipal)Util.panelMenu);
				dialogoTomarExamen.pack();
				Util.agregarIframe(dialogoTomarExamen);

				dialogoTomarExamen.doModal(this.getRootPane());
				dialogoTomarExamen.setVisible(true);
			}
			else
			{
				Util.panelMenu.cargarSubMenuPersona();
				Util.panelMenu.seleccionarPersona();				
			}

			
			//ExamenesUtils.mostrarPanelExamen(perExamen, Util.panelContenido);

		} catch (Exception e) {
			JOptionPaneTesterGral.showInternal(
					"Debe realizar por lo menos una evaluación", "Error",
					JOptionPane.ERROR_MESSAGE);
		}
	}

	public void imprimirResultado() {

		HashMap parameterMap = new HashMap();
		parameterMap.put("p_pexa_id", perExamen.getPexaId());
		new VentanaReportes(this, parameterMap, Constantes.RPT_PERSONA_EXAMEN);

	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton btnCancelarFoto;
	private javax.swing.JButton btnExaminar;
	private javax.swing.JButton btnGuardar;
	private javax.swing.JComboBox cbEstado;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JLabel lbAdjunto;
	private javax.swing.JTable tableDetalleExamen;
	// End of variables declaration//GEN-END:variables
	private PersonaExamen perExamen;
	private ResultadoDetalleExamenDefinition resultadoDetalleExamenService = (ResultadoDetalleExamenDefinition) ContextManager
			.getBizObject("resultadoDetalleExamenService");
	private LinkedList<ResultadoDetalleExamen> lstResultadoDetalleExamen = new LinkedList<ResultadoDetalleExamen>();
	private PersonaExamenDefinition personaExamenService = (PersonaExamenDefinition) ContextManager
			.getBizObject("personaExamenService");
}
