/*
 * PanelFinalizarExamen.java
 *
 * Created on __DATE__, __TIME__
 */

package frontend.paneles.examenes;

import java.io.File;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;

import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JRViewer;
import testerGeneral.business.ContextManager;
import testerGeneral.domain.Constantes;
import testerGeneral.domain.Examen;
import testerGeneral.domain.ExamenDetalle;
import testerGeneral.domain.PersonaExamen;
import testerGeneral.domain.ResultadoDetalleExamen;
import testerGeneral.service.ExamenDetalleDefinition;
import testerGeneral.service.PersonaExamenDefinition;
import testerGeneral.service.ResultadoDetalleExamenDefinition;
import examenes.util.ExamenesUtils;
import frontend.buttons.ButtonCancelarMini;
import frontend.buttons.ButtonExaminar;
import frontend.buttons.ButtonGuardar;
import frontend.components.JOptionPaneTesterGral;
import frontend.tablemodel.TableModelResultadoExamen;
import frontend.utils.Util;
import frontend.ventanas.VentanaExaminar;
import frontend.ventanas.VentanaReportes;

/**
 *
 * @author  __USER__
 */
public class PanelFinalizarExamen extends javax.swing.JPanel {

	/** Creates new form PanelFinalizarExamen */
	public PanelFinalizarExamen(PersonaExamen perExamen) {
		this.perExamen = perExamen;
		initComponents();
		Util.cargarDominios(cbEstado, Constantes.ESTADO_EXAMEN, false);
		detalleExamen();
		setTableModel(lstResultadoDetalleExamen);
	}

	public void detalleExamen() {
		try {
			ExamenDetalle detallesExamenen = new ExamenDetalle();
			detallesExamenen.setExamen(perExamen.getExamen());
			ExamenDetalleDefinition examenDetalleService = (ExamenDetalleDefinition) ContextManager
					.getBizObject("examenDetalleService");

			List<ExamenDetalle> detallesExamenes = examenDetalleService
					.getAll(detallesExamenen);

			for (int i = 0; i < detallesExamenes.size(); i++) {

				ResultadoDetalleExamen example = new ResultadoDetalleExamen();
				example.setExamenDetalle(detallesExamenes.get(i));
				example.setPersonaExamen(perExamen);
				List<ResultadoDetalleExamen> lstResultados = resultadoDetalleExamenService
						.getAll(example);

				if (lstResultados.size() < 1) {
					ResultadoDetalleExamen resultadoDetalleExamen = new ResultadoDetalleExamen();
					resultadoDetalleExamen.setExamenDetalle(detallesExamenes
							.get(i));
					lstResultadoDetalleExamen.add(resultadoDetalleExamen);
				} else {
					lstResultadoDetalleExamen.add(lstResultados.get(0));
				}

			}

		} catch (Exception e) {
			throw new RuntimeException(e);
		}
	}

	public void setTableModel(List lst) {
		TableModelResultadoExamen tableModel = new TableModelResultadoExamen();
		tableModel.setLst(lst);
		tableDetalleExamen.setModel(tableModel);
		tableDetalleExamen
				.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
		tableDetalleExamen.setAutoCreateRowSorter(true);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		tableDetalleExamen = new javax.swing.JTable();
		cbEstado = new javax.swing.JComboBox();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		btnGuardar = new ButtonGuardar();
		btnExaminar = new ButtonExaminar();
		btnCancelarFoto = new ButtonCancelarMini();

		jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null,
				"Detalle Exámen",
				javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
				javax.swing.border.TitledBorder.DEFAULT_POSITION,
				new java.awt.Font("Segoe UI", 3, 12)));
		jPanel1.setFocusable(false);

		tableDetalleExamen.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { "fsager", "No" }, { "vpaolini", "Si" },
						{ "jtesta", "Si" }, { null, null } }, new String[] {
						"Nombre usuario", "Habilitado" }) {
			Class[] types = new Class[] { java.lang.String.class,
					java.lang.String.class };
			boolean[] canEdit = new boolean[] { false, false };

			public Class getColumnClass(int columnIndex) {
				return types[columnIndex];
			}

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
		jScrollPane1.setViewportView(tableDetalleExamen);

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel1Layout.createSequentialGroup().addContainerGap()
						.addComponent(jScrollPane1,
								javax.swing.GroupLayout.DEFAULT_SIZE, 525,
								Short.MAX_VALUE).addContainerGap()));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel1Layout.createSequentialGroup().addComponent(
						jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE,
						170, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)));

		cbEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"Item 1", "Item 2", "Item 3", "Item 4" }));

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18));
		jLabel1.setText("Resultado General del Examen:");

		jLabel2.setText("Adjuntar Documentación:");

		btnGuardar.setText("Guardar");
		btnGuardar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnGuardarActionPerformed(evt);
			}
		});

		btnExaminar.setIcon(new ImageIcon(getClass().getResource(
				"/images/agregar.png")));
		btnExaminar.setToolTipText("Examinar");
		((ButtonExaminar) btnExaminar).init();
		btnExaminar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnExaminarActionPerformed(evt);
			}
		});

		btnCancelarFoto.setIcon(new ImageIcon(getClass().getResource(
				"/images/agregar.png")));
		btnCancelarFoto.setToolTipText("Examinar");
		((ButtonCancelarMini) btnCancelarFoto).init();
		btnCancelarFoto.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnCancelarFotoActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jPanel1,
																javax.swing.GroupLayout.Alignment.TRAILING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																layout
																		.createSequentialGroup()
																		.addContainerGap()
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								false)
																						.addGroup(
																								layout
																										.createSequentialGroup()
																										.addComponent(
																												jLabel2)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												btnExaminar,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												70,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												Short.MAX_VALUE)
																										.addComponent(
																												btnCancelarFoto,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												70,
																												javax.swing.GroupLayout.PREFERRED_SIZE))
																						.addComponent(
																								jLabel1))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				cbEstado,
																				0,
																				253,
																				Short.MAX_VALUE))
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																layout
																		.createSequentialGroup()
																		.addContainerGap(
																				481,
																				Short.MAX_VALUE)
																		.addComponent(
																				btnGuardar,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				80,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addContainerGap()));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(
												jPanel1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												17, Short.MAX_VALUE)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(jLabel2)
														.addComponent(
																btnExaminar,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																25,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																btnCancelarFoto,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																25,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(11, 11, 11)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel1)
														.addComponent(
																cbEstado,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(24, 24, 24)
										.addComponent(
												btnGuardar,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												20,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap()));

		((ButtonGuardar) btnGuardar).init();
	}// </editor-fold>
	//GEN-END:initComponents

	private void btnCancelarFotoActionPerformed(java.awt.event.ActionEvent evt) {
		perExamen.setPexaAdj(null);
		perExamen.setPexaNombreAdjunto(null);
	}

	private void btnExaminarActionPerformed(java.awt.event.ActionEvent evt) {
		final VentanaExaminar ventanaExaminar = new VentanaExaminar(
				JFileChooser.FILES_ONLY, JFileChooser.OPEN_DIALOG);
		ventanaExaminar.pack();
		Util.agregarIframe(ventanaExaminar);
		ventanaExaminar.doModal(this.getRootPane());
		ventanaExaminar.setVisible(true);

		if (ventanaExaminar.getRutaSeleccionada() != null) {

			try {

				
				File archivoSeleccionado = new File(ventanaExaminar
						.getRutaSeleccionada());
				
				String fileName=archivoSeleccionado.getName();
				byte[] bytes = testerGeneral.persistence.impl.Util.getBytesFromFile(archivoSeleccionado.getAbsolutePath());
				perExamen.setPexaNombreAdjunto(fileName);				
				perExamen.setPexaAdj(bytes);
				JOptionPaneTesterGral.showInternalMessageDialog(
						"Documentación Adjuntada Correctamente", "Adjuntar",
						JOptionPane.INFORMATION_MESSAGE);

			} catch (Exception e) {
				throw new RuntimeException(e);
			}
		}
	}

	private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {
		
		try {
			perExamen.setPexaEstado(Examen.ESTADO_FIN);
			perExamen.setPexaResultadoMedico(cbEstado.getSelectedItem()
					.toString());
			personaExamenService.update(perExamen);

			imprimirResultado();
			
			JOptionPaneTesterGral.showInternalMessageDialog(
					Constantes.MENSAJE_GUARDADO,
					Constantes.MENSAJE_GUARDADO_TIT,
					JOptionPane.INFORMATION_MESSAGE);

			ExamenesUtils.mostrarPanelExamenPsicometrico(perExamen, Util.panelContenido);
			
			

		} catch (Exception e) {
			JOptionPaneTesterGral.showInternal(
					"Debe realizar por lo menos una evaluación", "Error",
					JOptionPane.ERROR_MESSAGE);
		}
	}
	
	public void imprimirResultado()
	{

		HashMap parameterMap = new HashMap();
		parameterMap.put("p_pexa_id", perExamen.getPexaId());

		new VentanaReportes(this,parameterMap,Constantes.RPT_PERSONA_EXAMEN);

	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton btnCancelarFoto;
	private javax.swing.JButton btnExaminar;
	private javax.swing.JButton btnGuardar;
	private javax.swing.JComboBox cbEstado;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable tableDetalleExamen;
	// End of variables declaration//GEN-END:variables
	private PersonaExamen perExamen;
	private ResultadoDetalleExamenDefinition resultadoDetalleExamenService = (ResultadoDetalleExamenDefinition) ContextManager
			.getBizObject("resultadoDetalleExamenService");
	private LinkedList<ResultadoDetalleExamen> lstResultadoDetalleExamen = new LinkedList<ResultadoDetalleExamen>();
	private PersonaExamenDefinition personaExamenService = (PersonaExamenDefinition) ContextManager
			.getBizObject("personaExamenService");
}
