/*
 * PanelAnticipacion.java
 *
 * Created on __DATE__, __TIME__
 */

package frontend.paneles.examenes;

import javax.swing.JPanel;

import testerGeneral.domain.PersonaExamen;

/**
 * 
 * @author __USER__
 */
public class PanelExamenes extends javax.swing.JPanel implements Finalisable {

	private PersonaExamen personaExamen;

	public PanelExamenes(PersonaExamen personaExamen, PanelExamen panelAnimacion) {
		try {
			initComponents();

			this.personaExamen = personaExamen;

			panelDetalleExamen = new PanelDetalleExamen(personaExamen, this);

			panelAnimacion.setBtn(panelDetalleExamen.getBtnExamenPrimero());

			panelDetalle.add(panelDetalleExamen);

			if (personaExamen.getPersona() == null) {
				panelExaminado.setVisible(false);
				lbDemo.setVisible(true);
			} else {
				panelPersonaExamen = new PanelPersonaExamen(personaExamen
						.getPersona());
				panelExaminado.add(panelPersonaExamen);

				panelExaminado.setVisible(true);
				lbDemo.setVisible(false);
			}

			this.panelAnimacion.add((JPanel) panelAnimacion);

		} catch (Exception e) {
			throw new RuntimeException(e);
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		panelExaminado = new javax.swing.JPanel();
		panelDetalle = new javax.swing.JPanel();
		panelAnimacion = new PanelContenido();
		lbDemo = new javax.swing.JLabel();

		setForeground(new java.awt.Color(255, 0, 0));
		setFont(new java.awt.Font("Segoe UI", 3, 36));
		setMinimumSize(new java.awt.Dimension(600, 600));

		panelExaminado.setBorder(javax.swing.BorderFactory.createTitledBorder(
				null, "Examinado",
				javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
				javax.swing.border.TitledBorder.DEFAULT_POSITION,
				new java.awt.Font("Segoe UI", 3, 12)));
		panelExaminado.setLayout(new java.awt.GridLayout(1, 0));

		panelDetalle.setBorder(javax.swing.BorderFactory.createTitledBorder(
				null, "Detalle Examen",
				javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
				javax.swing.border.TitledBorder.DEFAULT_POSITION,
				new java.awt.Font("Segoe UI", 3, 12)));
		panelDetalle.setLayout(new java.awt.GridLayout(1, 0));

		panelAnimacion.setLayout(new java.awt.GridLayout(1, 0));

		lbDemo.setFont(new java.awt.Font("Segoe UI", 3, 48));
		lbDemo.setForeground(new java.awt.Color(255, 0, 0));
		lbDemo.setText("DEMOSTRACION");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addComponent(
												panelDetalle,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												286,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																panelAnimacion,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																784,
																Short.MAX_VALUE)
														.addComponent(
																panelExaminado,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																784,
																Short.MAX_VALUE)
														.addComponent(
																lbDemo,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																784,
																Short.MAX_VALUE))
										.addContainerGap()));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(panelDetalle,
								javax.swing.GroupLayout.DEFAULT_SIZE, 671,
								Short.MAX_VALUE)
						.addGroup(
								layout
										.createSequentialGroup()
										.addComponent(
												panelExaminado,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												92,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(lbDemo)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												panelAnimacion,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												488,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));
	}// </editor-fold>
	//GEN-END:initComponents

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JLabel lbDemo;
	private javax.swing.JPanel panelAnimacion;
	private javax.swing.JPanel panelDetalle;
	private javax.swing.JPanel panelExaminado;
	// End of variables declaration//GEN-END:variables

	private PanelPersonaExamen panelPersonaExamen;
	private PanelDetalleExamen panelDetalleExamen;

	@Override
	public void finalizar() {
		if (panelAnimacion.getComponent(0) instanceof Finalisable) {
			Finalisable f = (Finalisable) panelAnimacion.getComponent(0);
			f.finalizar();
		}
	}

	public javax.swing.JPanel getPanelAnimacion() {
		return panelAnimacion;
	}

	public void setPanelAnimacion(javax.swing.JPanel panelAnimacion) {
		this.panelAnimacion = panelAnimacion;
	}

}