/*
 * PanelExamenMultipleChoise.java
 *
 * Created on __DATE__, __TIME__
 */

package frontend.paneles;

import java.awt.Color;
import java.util.List;

import javax.swing.ButtonModel;
import javax.swing.ImageIcon;
import javax.swing.JRadioButton;
import javax.swing.JToggleButton;

import testerGeneral.business.PreguntasBiz;
import testerGeneral.domain.Constantes;
import testerGeneral.domain.DetalleExamenMultipleChoiceInterfaz;
import testerGeneral.domain.PersonaExamen;
import testerGeneral.domain.PreguntaInterfaz;
import testerGeneral.domain.RespuestaInterfaz;
import frontend.paneles.examenes.Finalisable;
import frontend.paneles.examenes.PanelDetalleExamen;
import frontend.paneles.examenes.PanelExamen;
import frontend.utils.Util;

/**
 *
 * @author  __USER__
 */
public class PanelExamenMultipleChoise extends javax.swing.JPanel implements
		Finalisable, PanelExamen {

	private PreguntaInterfaz pregunta;
	private PreguntasBiz preguntasBiz;
	private PersonaExamen personaExamen;

	/** Creates new form PanelExamenMultipleChoise */
	public PanelExamenMultipleChoise(PersonaExamen personaExamen,
			List<PreguntaInterfaz> preguntas) {
		this.personaExamen = personaExamen;

		initComponents();

		Util.mostrarError(lbError, null, true);
	}

	public void mostrarPregunta(String idPregunta) throws Exception {
		pregunta = preguntasBiz.getPreguntaFromId(idPregunta);
		mostrarPregunta();
	}

	public void mostrarPregunta() {

		try {
			Util.mostrarError(lbError, null, true);

			buttonGroupRespuestas.clearSelection();
			panelRespuestas.removeAll();
			panelRespuestas.setLayout(new java.awt.GridLayout(5, 1));

			txtPregunta.setText(pregunta.getPreDetalle());
			ImageIcon icon = new ImageIcon(pregunta.getPreImagen());
			lbFoto.setIcon(icon);
			List<RespuestaInterfaz> respuestas = preguntasBiz
					.getRespuestasFromPregunta(pregunta);

			Long time = personaExamen.getPexaFecha().getTime()
					* pregunta.getId() * 8412;
			String timeStr = time.toString() + "1928374650";

			DetalleExamenMultipleChoiceInterfaz detalleExamenMultipleChoice = preguntasBiz
					.getDetalleExamenMCFromPersonaExamen(personaExamen,
							pregunta);

			int[] posExito = new int[respuestas.size()];
			for (int i = 0; i < posExito.length; i++) {
				posExito[i] = -1;
			}

			int exitos = 0;
			for (int i = 0; i < timeStr.length() && exitos < respuestas.size(); i++) {
				try {
					char car = timeStr.charAt(i);
					String strCar = String.valueOf(car);
					int pos = Integer.valueOf(strCar);
					boolean posValida = true;
					for (int viajaPos : posExito) {
						if (viajaPos == pos) {
							posValida = false;
							break;
						}
					}

					if (posValida) {
						RespuestaInterfaz respuesta = respuestas.get(pos);
						String detalle = respuesta.getResDetalle().replaceAll(
								">", "&gt;");
						detalle = respuesta.getResDetalle().replaceAll("<",
								"&lt;");
						JRadioButton rdRespuesta = new JRadioButton("<html>"
								+ detalle + "</html>");
						rdRespuesta.setSize(300, 50);
						buttonGroupRespuestas.add(rdRespuesta);
						panelRespuestas.add(rdRespuesta);
						rdRespuesta.setActionCommand("" + respuesta.getId());

						if (detalleExamenMultipleChoice != null
								&& detalleExamenMultipleChoice.getRespuesta()
										.getId().equals(respuesta.getId())) {
							rdRespuesta.setSelected(true);
						}
						posExito[exitos] = pos;
						exitos++;
					}

				} catch (IndexOutOfBoundsException e) {

				}
			}

		} catch (Exception e) {
			throw new RuntimeException(e);
		}
	}

	public void setPreguntasBiz(PreguntasBiz preguntasBiz) {
		this.preguntasBiz = preguntasBiz;
	}

	public PreguntasBiz getPreguntasBiz() {
		return preguntasBiz;
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		buttonGroupRespuestas = new javax.swing.ButtonGroup();
		jScrollPane1 = new javax.swing.JScrollPane();
		txtPregunta = new javax.swing.JTextArea();
		panelRespuestas = new javax.swing.JPanel();
		btnSiguiente = new javax.swing.JButton();
		lbFoto = new javax.swing.JLabel();
		lbError = new javax.swing.JLabel();
		btnFinalizarExamen = new javax.swing.JButton();

		jScrollPane1.setMaximumSize(new java.awt.Dimension(176, 123));

		txtPregunta.setColumns(10);
		txtPregunta.setEditable(false);
		txtPregunta.setLineWrap(true);
		txtPregunta.setRows(2);
		txtPregunta.setWrapStyleWord(true);
		txtPregunta.setBorder(javax.swing.BorderFactory
				.createTitledBorder("Pregunta"));
		txtPregunta.setMaximumSize(new java.awt.Dimension(176, 123));
		jScrollPane1.setViewportView(txtPregunta);

		panelRespuestas.setBorder(javax.swing.BorderFactory
				.createTitledBorder("Respuestas"));
		panelRespuestas.setLayout(new java.awt.GridLayout(1, 0));

		btnSiguiente.setText("Confirmar");
		btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnSiguienteActionPerformed(evt);
			}
		});

		lbFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		lbFoto.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
		lbFoto.setMaximumSize(new java.awt.Dimension(246, 176));
		lbFoto.setMinimumSize(new java.awt.Dimension(246, 176));

		lbError.setForeground(new java.awt.Color(204, 0, 0));
		lbError.setIcon(new ImageIcon(getClass().getResource(
				Constantes.IMG_ERROR)));
		lbError.setText(Constantes.ERROR_SIN_RESULTADOS);

		btnFinalizarExamen.setText("Finalizar Examen");
		btnFinalizarExamen
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						btnFinalizarExamenActionPerformed(evt);
					}
				});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addContainerGap()
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								panelRespuestas,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								964,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING,
																								layout
																										.createSequentialGroup()
																										.addComponent(
																												lbError,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												743,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												Short.MAX_VALUE)
																										.addComponent(
																												btnSiguiente))
																						.addGroup(
																								layout
																										.createSequentialGroup()
																										.addComponent(
																												jScrollPane1,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												778,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																										.addComponent(
																												lbFoto,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												174,
																												Short.MAX_VALUE))))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGap(
																				415,
																				415,
																				415)
																		.addComponent(
																				btnFinalizarExamen)))
										.addContainerGap()));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jScrollPane1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																109,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																lbFoto,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																118,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												panelRespuestas,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																btnSiguiente)
														.addComponent(
																lbError,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																24,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(btnFinalizarExamen)
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));
	}// </editor-fold>
	//GEN-END:initComponents

	private void btnFinalizarExamenActionPerformed(
			java.awt.event.ActionEvent evt) {
		try {
			if(preguntasBiz.isExamenFinish(personaExamen))
			{
				preguntasBiz.finalizarExamen(personaExamen, "","");
				//TODO Mostrar reporte
				
			}
			else
			{
				//TODO informar que faltan cosas
			}

		} catch (Exception e) {
			throw new RuntimeException(e);
		}
	}

	private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {
		try {
			Util.mostrarError(lbError, null, true);
			ButtonModel buttonModel = buttonGroupRespuestas.getSelection();
			if (buttonModel != null) {

				RespuestaInterfaz respuesta = preguntasBiz
						.getRespuestasFromPregunta(buttonModel
								.getActionCommand());
				preguntasBiz.guardarDetalleExamen(personaExamen, pregunta,
						respuesta);

				btn.setForeground(Color.BLACK);
				Util.setIcon(btn, Constantes.IMG_ACEPTAR_SMALL);

				((PanelDetalleExamen) btn.getParent()).nextExamen(btn);

			} else {
				Util.mostrarError(lbError,
						"Debe seleccionar una respuesta antes de continuar.",
						false);
			}

		} catch (Exception e) {
			throw new RuntimeException(e);
		}

	}

	@Override
	public void finalizar() {
		// TODO Auto-generated method stub

	}

	@Override
	public void setBtn(JToggleButton btn) {
		this.btn = btn;
	}

	public JToggleButton getBtn() {
		return btn;
	}

	private JToggleButton btn;

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton btnFinalizarExamen;
	private javax.swing.JButton btnSiguiente;
	private javax.swing.ButtonGroup buttonGroupRespuestas;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JLabel lbError;
	private javax.swing.JLabel lbFoto;
	private javax.swing.JPanel panelRespuestas;
	private javax.swing.JTextArea txtPregunta;
	// End of variables declaration//GEN-END:variables

}