package ar.com.tecnologiaaplicada.domain;

// Generated 15-ene-2011 15:36:58 by Hibernate Tools 3.4.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DetalleLicencia generated by hbm2java
 */
@Entity
@Table(name = "detalle_licencia")
public class DetalleLicencia implements java.io.Serializable {

	private Long dlicId;
	private Licencia licencia;
	private ExamenDetalle examenDetalle;
	private String dlicActivaSn;

	public DetalleLicencia() {
	}

	public DetalleLicencia(Licencia licencia, ExamenDetalle examenDetalle,
			String dlicActivaSn) {
		this.licencia = licencia;
		this.examenDetalle = examenDetalle;
		this.dlicActivaSn = dlicActivaSn;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "DLIC_ID", unique = true, nullable = false)
	public Long getDlicId() {
		return this.dlicId;
	}

	public void setDlicId(Long dlicId) {
		this.dlicId = dlicId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "LIC_ID", nullable = false)
	public Licencia getLicencia() {
		return this.licencia;
	}

	public void setLicencia(Licencia licencia) {
		this.licencia = licencia;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "EXAD_ID", nullable = false)
	public ExamenDetalle getExamenDetalle() {
		return this.examenDetalle;
	}

	public void setExamenDetalle(ExamenDetalle examenDetalle) {
		this.examenDetalle = examenDetalle;
	}

	@Column(name = "DLIC_ACTIVA_SN", nullable = false, length = 1)
	public String getDlicActivaSn() {
		return this.dlicActivaSn;
	}

	public void setDlicActivaSn(String dlicActivaSn) {
		this.dlicActivaSn = dlicActivaSn;
	}

}
