package ar.com.tecnologiaaplicada.domain;

// Generated 15-ene-2011 15:36:58 by Hibernate Tools 3.4.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Examen generated by hbm2java
 */
@Entity
@Table(name = "EXAMEN",uniqueConstraints = @UniqueConstraint(columnNames = "EXA_CODIGO"))
public class Examen implements java.io.Serializable {


	private Long exaId;
	private String exaCodigo;
	private String exaNombre;
	private long exaOrden;
	//private Set<ExamenDetalle> examenDetalles = new HashSet<ExamenDetalle>(0);

	public Examen() {
	}

	public Examen(String exaCodigo, String exaNombre, long exaOrden) {
		this.exaCodigo = exaCodigo;
		this.exaNombre = exaNombre;
		this.exaOrden = exaOrden;
	}

	/*public Examen(String exaCodigo, String exaNombre, long exaOrden,
			Set<ExamenDetalle> examenDetalles) {
		this.exaCodigo = exaCodigo;
		this.exaNombre = exaNombre;
		this.exaOrden = exaOrden;
		this.examenDetalles = examenDetalles;
	}*/

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "EXA_ID", unique = true, nullable = false)
	public Long getExaId() {
		return this.exaId;
	}

	public void setExaId(Long exaId) {
		this.exaId = exaId;
	}

	@Column(name = "EXA_CODIGO", unique = true, nullable = false, length = 20)
	public String getExaCodigo() {
		return this.exaCodigo;
	}

	public void setExaCodigo(String exaCodigo) {
		this.exaCodigo = exaCodigo;
	}

	@Column(name = "EXA_NOMBRE", nullable = false, length = 100)
	public String getExaNombre() {
		return this.exaNombre;
	}

	public void setExaNombre(String exaNombre) {
		this.exaNombre = exaNombre;
	}

	@Column(name = "EXA_ORDEN", nullable = false)
	public long getExaOrden() {
		return this.exaOrden;
	}

	public void setExaOrden(long exaOrden) {
		this.exaOrden = exaOrden;
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "examen")
	public Set<ExamenDetalle> getExamenDetalles() {
		return this.examenDetalles;
	}

	public void setExamenDetalles(Set<ExamenDetalle> examenDetalles) {
		this.examenDetalles = examenDetalles;
	}*/

}
