package ar.com.tecnologiaaplicada.domain;

// Generated 15-ene-2011 15:36:58 by Hibernate Tools 3.4.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Propiedad generated by hbm2java
 */
@Entity
@Table(name = "PROPIEDAD")
public class Propiedad implements java.io.Serializable {

	private String propClave;
	private String propValor;
	private byte[] propBlob;

	public Propiedad() {
	}

	public Propiedad(String propClave, String propValor) {
		this.propClave = propClave;
		this.propValor = propValor;
	}

	public Propiedad(String propClave, String propValor, byte[] propBlob) {
		this.propClave = propClave;
		this.propValor = propValor;
		this.propBlob = propBlob;
	}

	@Id
	@Column(name = "PROP_CLAVE", unique = true, nullable = false, length = 200)
	public String getPropClave() {
		return this.propClave;
	}

	public void setPropClave(String propClave) {
		this.propClave = propClave;
	}

	@Column(name = "PROP_VALOR", nullable = false, length = 200)
	public String getPropValor() {
		return this.propValor;
	}

	public void setPropValor(String propValor) {
		this.propValor = propValor;
	}

	@Column(name = "PROP_BLOB")
	public byte[] getPropBlob() {
		return this.propBlob;
	}

	public void setPropBlob(byte[] propBlob) {
		this.propBlob = propBlob;
	}

}
