package actualizaciones;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * 
 * @author __USER__
 */
public class JDialogActualizar extends javax.swing.JDialog implements Runnable {

	/** Creates new form JDialogActualizar */
	public JDialogActualizar(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		try {
			this.setUndecorated(true);
			initComponents();
			this.setLocationRelativeTo(this);

			gestorActualizaciones = new GestorActualizaciones();
			gestorActualizaciones.start();

			Thread th = new Thread(this);
			th.start();
			jProgressBarProgresoActualizacion.setIndeterminate(true);
		} catch (RuntimeException ex) {
			GestorActualizaciones.setException(ex, "Error");
		} catch (Exception exc) {
			// log.error(exc.getMessage(), exc);
			System.exit(1);
		}

	}

	public void run() {
		while (true) {
			try {
				if (!gestorActualizaciones.isAlive()) {
					if (GestorActualizaciones.getException() == null) {
						jProgressBarProgresoActualizacion.setVisible(false);
						jLabelSeEstaActualizando
								.setText("Se ha actualizado correctamente a la última versión.");

						jLabelGifAnimado.setIcon(new javax.swing.ImageIcon(
								getClass().getResource("/imagenes/check.gif")));

					} else {
						System.out
								.println(GestorActualizaciones.getException());
						jLabelSeEstaActualizando.setText(GestorActualizaciones
								.getMensajeExcepcionParaElUsuario());
						jLabelGifAnimado.setIcon(new javax.swing.ImageIcon(
								getClass().getResource("/imagenes/error.gif")));
					}

					Thread.sleep(3500);// Espera 3 segundos, mostrando el
					// resultado de la actualización.
					try {
						Runtime.getRuntime()
								.exec(GestorActualizacionesUtil.getNombreAplicacion()+".exe");
					} catch (IOException ex) {
						//Logger.getLogger(JDialogActualizar.class.getName()).log(Level.SEVERE, null, ex);
					}

					System.exit(0);
				}
				Thread.sleep(50);
			} catch (InterruptedException ex) {
				Logger.getLogger(JDialogActualizar.class.getName()).log(
						Level.SEVERE, null, ex);
			}
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabelSeEstaActualizando = new javax.swing.JLabel();
		jLabelGifAnimado = new javax.swing.JLabel();
		jLabelTitulo = new javax.swing.JLabel();
		jProgressBarProgresoActualizacion = new javax.swing.JProgressBar();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		jLabelSeEstaActualizando
				.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabelSeEstaActualizando
				.setText("Se est\u00e1 actualizando el programa...");

		jLabelGifAnimado
				.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabelGifAnimado.setIcon(new javax.swing.ImageIcon(getClass()
				.getResource("/imagenes/updating.gif"))); // NOI18N

		jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 3, 14));
		jLabelTitulo.setText("Actualizaci\u00f3n de software");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jLabelSeEstaActualizando,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																458,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabelTitulo)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jLabelGifAnimado))
														.addComponent(
																jProgressBarProgresoActualizacion,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																458,
																Short.MAX_VALUE))
										.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup().addGroup(
						layout.createParallelGroup(
								javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(jLabelGifAnimado).addComponent(
										jLabelTitulo)).addGap(26, 26, 26)
						.addComponent(jLabelSeEstaActualizando,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE).addGap(18, 18, 18)
						.addComponent(jProgressBarProgresoActualizacion,
								javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE).addGap(
								14, 14, 14)));

		pack();
	}// </editor-fold>

	// GEN-END:initComponents

	// GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JLabel jLabelGifAnimado;
	private javax.swing.JLabel jLabelSeEstaActualizando;
	private javax.swing.JLabel jLabelTitulo;
	private javax.swing.JProgressBar jProgressBarProgresoActualizacion;
	// End of variables declaration//GEN-END:variables
	private GestorActualizaciones gestorActualizaciones;
}