/*
 * PanelImagenFinal.java
 *
 * Created on __DATE__, __TIME__
 */

package frontend.components;

import java.awt.Graphics;
import java.awt.Image;

/**
 *
 * @author  __USER__
 */
public class PanelImagenFinal extends javax.swing.JPanel {

	/** Creates new form PanelImagenFinal */
	Image img;
	
	public Image getImg() {
		return img;
	}

	public void setImg(Image img) {
		this.img = img;
	}

	public PanelImagenFinal() {
		initComponents();
	}
	
	@Override
	protected void paintComponent(Graphics g) {
		super.paintComponent(g);  
		if(img!=null)
			g.drawImage(img,0,0,this);
		
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 400,
				Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 300,
				Short.MAX_VALUE));
	}// </editor-fold>
	//GEN-END:initComponents

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	// End of variables declaration//GEN-END:variables

}