/*
 * PanelAnticipacionUsuario.java
 *
 * Created on __DATE__, __TIME__
 */

package frontend.paneles.psicometrico.cooordinacion.bimanual;

import frontend.paneles.examenes.PanelCaptura;

/**
 *
 * @author  __USER__
 */
public class PanelCoordinacionBimanualUsuario extends javax.swing.JPanel {

	/** Creates new form PanelAnticipacionUsuario */

	public PanelCoordinacionBimanualUsuario(
			PanelCoordinacionBimanualAnimacion panelCoordinacionBimanualAnimacion,
			boolean src) {
		this.src = src;
		initComponents();
		jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
		jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

		this.panelCoordinacionBimanualAnimacion = panelCoordinacionBimanualAnimacion;
		if (src) {
			jTextArea1.setFont(new java.awt.Font("Monospaced", 3, 12));
			panelCaptura = new PanelCaptura(panelCoordinacionBimanualAnimacion);
			panelContenido.add(panelCaptura);
		} else {
			jTextArea1.setFont(new java.awt.Font("Monospaced", 3, 16));
			panelContenido.add(panelCoordinacionBimanualAnimacion);
		}

		this.validate();
	}

	public void init() {
		panelContenido.removeAll();
		if (src)
			panelContenido.add(panelCaptura);
		else
			panelContenido.add(panelCoordinacionBimanualAnimacion);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();
		panelContenido = new javax.swing.JPanel();

		jTextArea1.setColumns(20);
		jTextArea1.setEditable(false);
		jTextArea1.setFont(new java.awt.Font("Monospaced", 3, 24));
		jTextArea1.setForeground(new java.awt.Color(255, 0, 0));
		jTextArea1.setLineWrap(true);
		jTextArea1.setRows(2);
		jTextArea1
				.setText("Consigna: mantener los vehiculos dentro de los caminos.");
		jTextArea1.setWrapStyleWord(true);
		jScrollPane1.setViewportView(jTextArea1);

		panelContenido.setLayout(new java.awt.GridLayout(1, 0));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGap(0, 838, Short.MAX_VALUE)
						.addGroup(
								layout
										.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(
												javax.swing.GroupLayout.Alignment.TRAILING,
												layout
														.createSequentialGroup()
														.addContainerGap()
														.addGroup(
																layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING)
																		.addComponent(
																				jScrollPane1,
																				javax.swing.GroupLayout.Alignment.LEADING,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				814,
																				Short.MAX_VALUE)
																		.addComponent(
																				panelContenido,
																				javax.swing.GroupLayout.Alignment.LEADING,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				814,
																				Short.MAX_VALUE))
														.addContainerGap())));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGap(0, 509, Short.MAX_VALUE)
						.addGroup(
								layout
										.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(
												javax.swing.GroupLayout.Alignment.TRAILING,
												layout
														.createSequentialGroup()
														.addContainerGap()
														.addComponent(
																jScrollPane1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																58,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGap(4, 4, 4)
														.addComponent(
																panelContenido,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																421,
																Short.MAX_VALUE)
														.addContainerGap())));
	}// </editor-fold>
	//GEN-END:initComponents

	public boolean isRun() {
		boolean isRun = false;
		if (panelCaptura != null)
			isRun = panelCaptura.isRun();
		return isRun;
	}

	public void setRun(boolean run) {
		if (panelCaptura != null)
			panelCaptura.setRun(run);
	}

	
	public javax.swing.JScrollPane getJScrollPane1() {
		return jScrollPane1;
	}

	public void setJScrollPane1(javax.swing.JScrollPane scrollPane1) {
		jScrollPane1 = scrollPane1;
	}

	public javax.swing.JTextArea getJTextArea1() {
		return jTextArea1;
	}

	public void setJTextArea1(javax.swing.JTextArea textArea1) {
		jTextArea1 = textArea1;
	}

	public javax.swing.JPanel getPanelContenido() {
		return panelContenido;
	}

	public void setPanelContenido(javax.swing.JPanel panelContenido) {
		this.panelContenido = panelContenido;
	}

	public PanelCoordinacionBimanualAnimacion getPanelCoordinacionBimanualAnimacion() {
		return panelCoordinacionBimanualAnimacion;
	}

	public void setPanelCoordinacionBimanualAnimacion(
			PanelCoordinacionBimanualAnimacion panelCoordinacionBimanualAnimacion) {
		panelCoordinacionBimanualAnimacion = panelCoordinacionBimanualAnimacion;
	}

	public boolean isSrc() {
		return src;
	}

	public void setSrc(boolean src) {
		this.src = src;
	}

	public PanelCaptura getPanelCaptura() {
		return panelCaptura;
	}

	public void setPanelCaptura(PanelCaptura panelCaptura) {
		this.panelCaptura = panelCaptura;
	}


	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextArea jTextArea1;
	private javax.swing.JPanel panelContenido;
	// End of variables declaration//GEN-END:variables
	private PanelCoordinacionBimanualAnimacion panelCoordinacionBimanualAnimacion;
	private boolean src;
	private PanelCaptura panelCaptura;
}