/*
 * PanelRespuesta.java
 *
 * Created on __DATE__, __TIME__
 */

package opcionesmultiples.paneles;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

import opcionesmultiples.domain.Pregunta;
import opcionesmultiples.domain.Respuesta;
import opcionesmultiples.service.RespuestaDefinition;
import testerGeneral.business.ContextManager;
import testerGeneral.domain.Constantes;
import testerGeneral.domain.Dominio;
import frontend.buttons.ButtonCancelarConTexto;
import frontend.buttons.ButtonGuardar;
import frontend.components.JOptionPaneTesterGral;
import frontend.utils.Util;
import frontend.ventanas.JInternalFrameTesterGral;

/**
 *
 * @author  __USER__
 */
public class PanelRespuesta extends javax.swing.JPanel {

	/** Creates new form PanelRespuesta */
	public PanelRespuesta(Respuesta respuesta, JInternalFrameTesterGral jif) {
		this.jif = jif;
		this.respuesta = respuesta;
		
		initComponents();
		Util.mostrarError(lbError, null, true);
		
		if(respuesta.getId()!=null){
			txtRespuesta.setText(respuesta.getResDetalle());
			if(respuesta.getResCorrecta().equals("S"))
				checkCorrecta.setSelected(true);
		}
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		btnGuardar = new ButtonGuardar();
		btnCancelar = new ButtonCancelarConTexto();
		jLabel9 = new javax.swing.JLabel();
		jScrollPane3 = new javax.swing.JScrollPane();
		txtRespuesta = new javax.swing.JTextArea();
		checkCorrecta = new javax.swing.JCheckBox();
		lbError = new javax.swing.JLabel();

		btnGuardar.setText("Guardar");
		btnGuardar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnGuardarActionPerformed(evt);
			}
		});

		btnCancelar.setText("Cancelar");
		btnCancelar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnCancelarActionPerformed(evt);
			}
		});

		jLabel9.setText("Respuesta:");

		txtRespuesta.setColumns(20);
		txtRespuesta.setLineWrap(true);
		txtRespuesta.setRows(3);
		txtRespuesta.setWrapStyleWord(true);
		jScrollPane3.setViewportView(txtRespuesta);

		checkCorrecta.setText("Es Correcta");
		checkCorrecta.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				checkCorrectaActionPerformed(evt);
			}
		});

		lbError.setBackground(new java.awt.Color(204, 0, 0));
		lbError.setForeground(new java.awt.Color(204, 0, 0));
		lbError.setIcon(new ImageIcon(getClass().getResource(
				Constantes.IMG_ERROR)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								checkCorrecta)
																						.addGroup(
																								layout
																										.createSequentialGroup()
																										.addComponent(
																												jLabel9)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																										.addComponent(
																												jScrollPane3,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												338,
																												javax.swing.GroupLayout.PREFERRED_SIZE)))
																		.addContainerGap(
																				19,
																				Short.MAX_VALUE))
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																layout
																		.createSequentialGroup()
																		.addComponent(
																				btnGuardar,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				80,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				btnCancelar,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				80,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(
																				117,
																				117,
																				117))
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																layout
																		.createSequentialGroup()
																		.addComponent(
																				lbError,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				413,
																				Short.MAX_VALUE)
																		.addContainerGap()))));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel9)
														.addComponent(
																jScrollPane3,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addComponent(checkCorrecta)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												lbError,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												24,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																btnGuardar,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																20,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																btnCancelar,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																20,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap()));

		((ButtonGuardar) btnGuardar).init();
		((ButtonCancelarConTexto) btnCancelar).init();
	}// </editor-fold>
	//GEN-END:initComponents

	private void checkCorrectaActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {
		jif.setClosed(true);
	}

	private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {
		Util.mostrarError(lbError, null, true);
		if (validarRespuesta()) {
			boolean isUpdate = true;

			if (respuesta.getId() == null)
				isUpdate = false;

			respuesta.setResDetalle(txtRespuesta.getText());

			respuesta.setResCorrecta("N");
			if (checkCorrecta.isSelected()) {
				respuesta.setResCorrecta("S");
			}

			try {

				if (isUpdate) {
					respuestaService.update(respuesta);
				} else {
					respuestaService.insert(respuesta);
				}

				/*JOptionPaneTesterGral.showInternalMessageDialog(
						Constantes.MENSAJE_GUARDADO,
						Constantes.MENSAJE_GUARDADO_TIT,
						JOptionPane.INFORMATION_MESSAGE);*/
				jif.setClosed(true);

			} catch (Exception e) {
				throw new RuntimeException(e);
			}

		}
	}

	public boolean validarRespuesta() {
		if (txtRespuesta.getText() == null || txtRespuesta.getText().equals("")) {
			Util.mostrarError(lbError, "Debe especificar una respuesta", false);
			return false;
		}

		return true;

	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton btnCancelar;
	private javax.swing.JButton btnGuardar;
	private javax.swing.JCheckBox checkCorrecta;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JScrollPane jScrollPane3;
	private javax.swing.JLabel lbError;
	private javax.swing.JTextArea txtRespuesta;
	// End of variables declaration//GEN-END:variables

	private JInternalFrameTesterGral jif;
	private RespuestaDefinition respuestaService = (RespuestaDefinition) ContextManager
			.getBizObject("respuestaService");
	private Respuesta respuesta;

}