/*
 * PanelAgudezaVisual.java
 *
 * Created on __DATE__, __TIME__
 */

package frontend.paneles.vision;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Set;

import javax.swing.ImageIcon;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JToggleButton;

import testerGeneral.business.ContextManager;
import testerGeneral.domain.Constantes;
import testerGeneral.domain.Examen;
import testerGeneral.domain.ExamenDetalle;
import testerGeneral.domain.PersonaExamen;
import testerGeneral.domain.Resultado;
import testerGeneral.domain.ResultadoDetalleExamen;
import testerGeneral.exceptions.ExceptionIsNotHadware;
import testerGeneral.service.ExamenDetalleDefinition;
import testerGeneral.service.PersonaExamenDefinition;
import testerGeneral.service.ResultadoDetalleExamenDefinition;
import testerGeneral.threads.ThreadTrama;
import examenes.psicometrico.domain.TramaVision;
import examenes.util.ExamenesUtils;
import frontend.components.JOptionPaneTesterGral;
import frontend.paneles.examenes.Finalisable;
import frontend.paneles.examenes.PanelDetalleExamen;
import frontend.paneles.examenes.PanelExamen;
import frontend.utils.Util;

/**
 *
 * @author  __USER__
 */
public class PanelCampimetria extends javax.swing.JPanel implements
		Finalisable, PanelExamen {

	private JToggleButton btn;
	private PersonaExamen personaExamen;
	private ExamenDetalle exaDetalle;
	private List<Resultado> resultados = new ArrayList<Resultado>();
	private static final int LINEA_PROFECIONAL = 6;
	private static final int LINEA_PARTICULAR = 5;
	private ThreadTrama thTrama;

	/** Creates new form PanelAgudezaVisual */
	public PanelCampimetria(JToggleButton btn, PersonaExamen personaExamen) {
		this.btn = btn;
		this.personaExamen = personaExamen;
		initComponents();
		Util.mostrarError(lbError, null, true);

		try {
			ExamenDetalleDefinition examenDetalleService = (ExamenDetalleDefinition) ContextManager
					.getBizObject("examenDetalleService");
			exaDetalle = new ExamenDetalle();
			exaDetalle
					.setExadCodigo(ExamenDetalle.EXAD_CODIGO_TEST_CAMPIMETRIA);
			exaDetalle = (ExamenDetalle) examenDetalleService
					.getAll(exaDetalle).get(0);

		} catch (Exception e) {
			throw new RuntimeException(e);
		}
		inicializarThreads();
	}

	public void inicializarThreads() {

		try {
			thTrama = new ThreadTrama(new TramaVision());
			Util.thTrama = thTrama;
			thTrama.setEjecucion(99999);
			thTrama.start();
			
			
			thTrama.sendOrden(ThreadTrama.ORDEN_IR_TEST8);
			
			
		} catch (ExceptionIsNotHadware e) {
			JOptionPaneTesterGral.showInternalMessageDialog(e.getMessage(),
					"Error", JOptionPane.ERROR_MESSAGE);
		}

	}


	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		btnGuardar = new javax.swing.JToggleButton();
		lbError = new javax.swing.JLabel();
		jLayeredPane1 = new javax.swing.JLayeredPane();
		jPanel1 = new javax.swing.JPanel();
		jCheckNasalSup = new javax.swing.JCheckBox();
		jCheckNasalInf = new javax.swing.JCheckBox();
		jPanel2 = new javax.swing.JPanel();
		jCheckDer85 = new javax.swing.JCheckBox();
		jCheckDer70 = new javax.swing.JCheckBox();
		jCheckDer55 = new javax.swing.JCheckBox();
		jPanel4 = new javax.swing.JPanel();
		jCheckIzq85 = new javax.swing.JCheckBox();
		jCheckIzq70 = new javax.swing.JCheckBox();
		jCheckIzq55 = new javax.swing.JCheckBox();

		setBorder(javax.swing.BorderFactory.createTitledBorder(""));

		btnGuardar.setFont(new java.awt.Font("Segoe UI", 3, 14));
		btnGuardar.setForeground(new java.awt.Color(0, 0, 255));
		btnGuardar.setText("Guardar Resultados");
		btnGuardar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnGuardarActionPerformed(evt);
			}
		});

		lbError.setForeground(new java.awt.Color(204, 0, 0));
		lbError.setIcon(new ImageIcon(getClass().getResource(
				Constantes.IMG_ERROR)));
		lbError.setText(Constantes.ERROR_SIN_RESULTADOS);

		jLayeredPane1.setBorder(javax.swing.BorderFactory
				.createTitledBorder(""));

		jPanel1
				.setBorder(javax.swing.BorderFactory
						.createTitledBorder("Nasal"));

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGap(38, 38, 38)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jCheckNasalInf)
														.addComponent(
																jCheckNasalSup))
										.addContainerGap(39, Short.MAX_VALUE)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel1Layout.createSequentialGroup().addGap(31, 31, 31)
						.addComponent(jCheckNasalSup).addGap(34, 34, 34)
						.addComponent(jCheckNasalInf).addContainerGap(44,
								Short.MAX_VALUE)));

		jPanel1.setBounds(220, 40, 110, 180);
		jLayeredPane1.add(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jPanel2.setBorder(javax.swing.BorderFactory
				.createTitledBorder("Ojo derecho"));

		jCheckDer85.setText("85\u00b0");

		jCheckDer70.setText("70\u00b0");

		jCheckDer55.setText("55\u00b0");

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel2Layout.createSequentialGroup().addGap(61, 61, 61)
						.addComponent(jCheckDer70).addContainerGap(64,
								Short.MAX_VALUE)).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				jPanel2Layout.createSequentialGroup().addContainerGap(117,
						Short.MAX_VALUE).addComponent(jCheckDer85)
						.addContainerGap()).addGroup(
				jPanel2Layout.createSequentialGroup().addContainerGap()
						.addComponent(jCheckDer55).addContainerGap(117,
								Short.MAX_VALUE)));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel2Layout.createSequentialGroup().addContainerGap()
						.addComponent(jCheckDer85).addGap(27, 27, 27)
						.addComponent(jCheckDer70).addGap(28, 28, 28)
						.addComponent(jCheckDer55).addContainerGap(12,
								Short.MAX_VALUE)));

		jPanel2.setBounds(330, 40, 180, 180);
		jLayeredPane1.add(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jPanel4.setBorder(javax.swing.BorderFactory
				.createTitledBorder("Ojo izquierdo"));

		jCheckIzq85.setText("85\u00b0");

		jCheckIzq70.setText("70\u00b0");

		jCheckIzq55.setText("55\u00b0");

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(
				jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout.setHorizontalGroup(jPanel4Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel4Layout.createSequentialGroup().addContainerGap()
						.addComponent(jCheckIzq85).addContainerGap(137,
								Short.MAX_VALUE)).addGroup(
				jPanel4Layout.createSequentialGroup().addGap(58, 58, 58)
						.addComponent(jCheckIzq70).addContainerGap(87,
								Short.MAX_VALUE)).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				jPanel4Layout.createSequentialGroup().addContainerGap(101,
						Short.MAX_VALUE).addComponent(jCheckIzq55).addGap(44,
						44, 44)));
		jPanel4Layout.setVerticalGroup(jPanel4Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel4Layout.createSequentialGroup().addContainerGap()
						.addComponent(jCheckIzq85).addGap(26, 26, 26)
						.addComponent(jCheckIzq70).addGap(27, 27, 27)
						.addComponent(jCheckIzq55).addContainerGap(14,
								Short.MAX_VALUE)));

		jPanel4.setBounds(20, 40, 200, 180);
		jLayeredPane1.add(jPanel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																false)
														.addGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																layout
																		.createSequentialGroup()
																		.addComponent(
																				lbError,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				304,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addComponent(
																				btnGuardar))
														.addComponent(
																jLayeredPane1,
																javax.swing.GroupLayout.Alignment.LEADING,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																548,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap(325, Short.MAX_VALUE)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addComponent(
												jLayeredPane1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												341,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																lbError,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																24,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																btnGuardar))
										.addGap(53, 53, 53)));
	}// </editor-fold>
	//GEN-END:initComponents

	public boolean isExamenValid() {
		Util.mostrarError(lbError, null, true);

		/*if (jCheckBoxBinocular.isSelected()
				&& !isLineaValueValid(jFormattedLineaBinocular)) {
			Util
					.mostrarError(
							lbError,
							"Debe ingresar la línea correcta para binocular. Valores entre 1 y 7.",
							false);
			return false;
		} else if (jCheckBoxMonoIzq.isSelected()
				&& !isLineaValueValid(jFormattedMonoIzq)) {
			Util
					.mostrarError(
							lbError,
							"Debe ingresar la línea correcta para monocular izquierdo. Valores entre 1 y 7.",
							false);
			return false;
		} else if (jCheckBoxMonoDer.isSelected()
				&& !isLineaValueValid(jFormattedMonoDer)) {
			Util
					.mostrarError(
							lbError,
							"Debe ingresar la línea correcta para monocular derecho. Valores entre 1 y 7.",
							false);
			return false;
		}*/

		return true;
	}

	public void cargarResultados() {
		/*resultados.clear();
		Resultado res = new Resultado();
		res.setResEtapa(0l);
		if (jCheckBoxBinocular.isSelected()) {
			res.setResEtapaDesc("Visión binocular");
			res
					.setResValor1(Double.valueOf(jFormattedLineaBinocular
							.getText()));
			resultados.add(res);
		}

		res = new Resultado();
		res.setResEtapa(1l);
		if (jCheckBoxMonoIzq.isSelected()) {
			res.setResEtapaDesc("Visión monocular izquierdo");
			res.setResValor1(Double.valueOf(jFormattedMonoIzq.getText()));
			resultados.add(res);
		}

		res = new Resultado();
		res.setResEtapa(2l);
		if (jCheckBoxMonoDer.isSelected()) {
			res.setResEtapaDesc("Visión monocular derecho");
			res.setResValor1(Double.valueOf(jFormattedMonoDer.getText()));
			resultados.add(res);
		}*/
	}

	public String getResultado() {
		/*if (jCheckBoxBinocular.isSelected()) {
			int lineaBinocular = Integer.valueOf(jFormattedLineaBinocular
					.getText());
			if (!isAprobed(lineaBinocular))
				return Examen.RESULTADO_FUERA;
		}

		if (jCheckBoxMonoIzq.isSelected()) {
			int lineaMonoIzq = Integer.valueOf(jFormattedMonoIzq.getText());
			if (!isAprobed(lineaMonoIzq))
				return Examen.RESULTADO_FUERA;
		}

		if (jCheckBoxMonoDer.isSelected()) {
			int lineaMonoDer = Integer.valueOf(jFormattedMonoDer.getText());
			if (!isAprobed(lineaMonoDer))
				return Examen.RESULTADO_FUERA;
		}*/

		return Examen.RESULTADO_DENTRO;
	}

	public boolean isAprobed(int valor) {
		/*if (this.personaExamen.getPexaTipoExamen().equals("Profesional")
				&& valor < LINEA_PROFECIONAL)
			return false;

		if (this.personaExamen.getPexaTipoExamen().equals("Particular")
				&& valor < LINEA_PARTICULAR)
			return false;*/

		return true;
	}

	private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {
		btnGuardar.setSelected(false);
		ResultadoDetalleExamenDefinition resultadoDetalleExamenService = (ResultadoDetalleExamenDefinition) ContextManager
				.getBizObject("resultadoDetalleExamenService");
		PersonaExamenDefinition personaExamenService = (PersonaExamenDefinition) ContextManager
				.getBizObject("personaExamenService");

		try {

			if (personaExamen != null && personaExamen.getPexaId() == null) {
				personaExamen.setPexaEstado("INICIADO");
				personaExamen.setPexaFecha(new Date());
				personaExamenService.insert(personaExamen);
			}

			if (isExamenValid()) {
				ResultadoDetalleExamen resultadoDetalleExamen = new ResultadoDetalleExamen();
				resultadoDetalleExamen.setExamenDetalle(exaDetalle);
				resultadoDetalleExamen.setPersonaExamen(personaExamen);
				List lstResultados = resultadoDetalleExamenService
						.getAll(resultadoDetalleExamen);

				if (lstResultados.size() < 1) {
					resultadoDetalleExamenService
							.insert(resultadoDetalleExamen);
				} else if (lstResultados.size() == 1) {
					resultadoDetalleExamen = (ResultadoDetalleExamen) lstResultados
							.get(0);
				}

				cargarResultados();
				String detalleResultado = new String();
				Set setResultados = resultadoDetalleExamen.getResultados();
				setResultados.clear();
				for (int i = 0; i < this.resultados.size(); i++) {
					this.resultados.get(i).setResultadoDetalleExamen(
							resultadoDetalleExamen);
					setResultados.add(this.resultados.get(i));
					detalleResultado = detalleResultado
							+ this.resultados.get(i).getResEtapaDesc() + ": "
							+ this.resultados.get(i).getResValor1().intValue()
							+ ". ";
				}

				String resultado = getResultado();

				resultadoDetalleExamen.setRdeResultado(resultado);
				resultadoDetalleExamen.setRdeDetalleResultado(detalleResultado);

				resultadoDetalleExamenService.update(resultadoDetalleExamen);

				btn.setForeground(Color.BLACK);
				Util.setIcon(btn, Constantes.IMG_ACEPTAR_SMALL);

				((PanelDetalleExamen) btn.getParent()).nextExamen(btn);
			}

		} catch (Exception e) {
			throw new RuntimeException(e);
		}
	}

	@Override
	public void finalizar() {
		// TODO Auto-generated method stub

	}

	@Override
	public void setBtn(JToggleButton btn) {
		this.btn = btn;
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JToggleButton btnGuardar;
	private javax.swing.JCheckBox jCheckDer55;
	private javax.swing.JCheckBox jCheckDer70;
	private javax.swing.JCheckBox jCheckDer85;
	private javax.swing.JCheckBox jCheckIzq55;
	private javax.swing.JCheckBox jCheckIzq70;
	private javax.swing.JCheckBox jCheckIzq85;
	private javax.swing.JCheckBox jCheckNasalInf;
	private javax.swing.JCheckBox jCheckNasalSup;
	private javax.swing.JLayeredPane jLayeredPane1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JLabel lbError;
	// End of variables declaration//GEN-END:variables

}